### ISSUE TITLE
Authentication failing at first-time use.

### ISSUE THREAD

**Issue by Charlweed** [icloud-photos-downloader/icloud_photos_downloader#1011]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
icloudpd fails with exception `keyring.errors.KeyringLocked: Failed to unlock the collection!` before prompting for password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. Version of the app, OS/System, and minimum command line to reproduce. )
I am trying to use icloudpd for the first time. My system is Ubuntu 20.4 LTS, default python is python 3.10.2. I installed icloudpd via pip.  icloudpd version:1.24.4, commit sha:8222e8e, commit timestamp:Mon Nov 18 20:43:08 2024 PST

I have read the README.md, `install.md`, and `authentication.md`. Upon first attempt, icloudpd failed with the above KeyringLocked error. As suggested in ` authentication.md`, I waited over an hour before attempting to continue. I tried icloudpd with and without the `--mfa-provider console` option, all with the same error. I then focused on using --auth-only.

1. `icloudpd --username my@emailaddress.name --auth-only --mfa-provider console`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to be prompted for a password, then, I assume a 2FA code, and an alert to come to my phone.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
````
2024-12-01 13:55:52 DEBUG    Authenticating...
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 51, in authenticate_
  File "pyicloud_ipd/utils.py", line 37, in get_password_from_keyring
  File "keyring/core.py", line 56, in get_password
  File "keyring/backends/chainer.py", line 49, in get_password
  File "keyring/backends/SecretService.py", line 79, in get_password
  File "keyring/backends/SecretService.py", line 68, in get_preferred_collection
keyring.errors.KeyringLocked: Failed to unlock the collection!
[523274] Failed to execute script 'icloudpd' due to unhandled exception!
````
If I try to provide my password on the command line:
1. `icloudpd --username my@emailaddress.name --password 'secretchars' --auth-only`
``` Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[523196] Failed to execute script 'icloudpd' due to unhandled exception!
```
My password does contain characters that need to be escaped from the shell, but I use single quotes, and expect that to solve character issues.

## Context
[NOTE]: # ( Tell us why expected behavior is valuable )

[NOTE]: # ( Give us any additional information you may have. )
I would not be surprised if this is a python config issue for my Ubuntu 20.4, python 3.10 system. But I have no idea what might be misconfigured. I will eventually try again in a venv and python 3.11

**Comment by Charlweed** [comment]
Thank Andrey, I've now googled:  `python keyring linux "Failed to unlock the collection"` and I see that there is stuff to diagnose. I'll update here when I learn more.

**Comment by Charlweed** [comment]
My issue seems to come from trying to use the keyring service without running a desktop gui. I opened a (remote) desktop session, ran icloudpd. gnome asked my for my local password, then icloudpd asked me for my icloud password. So I'm closing this. Issue. Thanks for your time.

On The Other Hand, icloudpd still is not working for me, I get 
````
2024-12-01 16:14:49 DEBUG    Authenticating...
iCloud Password: 
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[529234] Failed to execute script 'icloudpd' due to unhandled exception!
````
So I still have some stuff to work out.

**Comment by AndreyNikiforov** [comment]
> PyiCloudFailedLoginException

There are open issues about that, so it is not your `icloudpd` setup as far as i can tell
