### ISSUE TITLE
icloudpd 1.25.0 hangs on login (Fedora 40)

### ISSUE THREAD

**Issue by LarsPoulsen** [icloud-photos-downloader/icloud_photos_downloader#1016]
## Overview
```
icloudpd -u lars@beagle-ears.com -p xxxxxxx --recent 1 --folder-structure {:%Y/%m} --directory /pictures/Imports/ffff
2024-12-03 13:20:15 DEBUG    Authenticating...
2024-12-03 13:20:16 ERROR    Authentication required for Account. (421)
[Hangs here for several minutes until I hit Ctrl/C]
{Apple sends be a 6-digit code, but I never get prompted to enter it.]
^C
Aborted!
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 5, in <module>
    from icloudpd import __main__
  File "/usr/local/lib/python3.12/site-packages/icloudpd/__main__.py", line 5, in <module>
    sys.exit(subprocess.call([os.path.join(os.path.dirname(__file__), "icloudpd"), *sys.argv[1:]]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 391, in call
    return p.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by AndreyNikiforov** [comment]
How did you install `icloudpd`?

try:
- simple cli, e.g. "icloudpd -u your@apple.id --password-provider console --mfa-provider console --auth-only"
- binary package downloaded from github release; docker (if you installed with pip)

**Comment by LarsPoulsen** [comment]
Your `--auth-only` example worked.
After trying some variations, it looks like it works with `--password-provider console` and fails with `-p <password>`

**Comment by AndreyNikiforov** [comment]
> Your `--auth-only` example worked. After trying some variations, it looks like it works with `--password-provider console` and fails with `-p <password>`

Most likely shell impacts the way password passed with `-p` parameter - don't use it
