### ISSUE TITLE
ERROR private db access disabled for this account (probably ADP)

### ISSUE THREAD

**Issue by internationils** [icloud-photos-downloader/icloud_photos_downloader#1024]
Hello, just installed it and logged in, and got this error. I though it would be good to handle the exception cleanly and point to one of the apple sites / resources or mention the fact that icloudpd does not work with ADP turned on. Thanks!

Related:
- https://github.com/boredazfcuk/docker-icloudpd/issues/397
- https://github.com/boredazfcuk/docker-icloudpd/issues/390
- https://support.apple.com/en-au/108756
- https://forums.developer.apple.com/forums/thread/743377
- https://discussions.apple.com/thread/254893007?sortBy=rank

```
2024-12-22 19:13:10 INFO     Great, you're all set up. The script can now be run without user interaction until 2FA expires.
You can set up email notifications for when the two-factor authentication expires.
(Use --help to view information about SMTP options.)
2024-12-22 19:13:10 ERROR    private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 753, in main
  File "icloudpd/base.py", line 1235, in core
  File "pyicloud_ipd/base.py", line 603, in photos
  File "pyicloud_ipd/services/photos.py", line 283, in __init__
  File "pyicloud_ipd/services/photos.py", line 170, in __init__
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/session.py", line 167, in request
  File "pyicloud_ipd/session.py", line 196, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)
[6210] Failed to execute script 'icloudpd' due to unhandled exception!

```

**Comment by AndreyNikiforov** [comment]
Is it confirmed that for access blocked by ADP, iCloud.com returns quoted "ACCESS_DENIED" error? If it is, that extending error message with ADP link should be a easy.

**Comment by jkraemer** [comment]
I've encountered the exact same error, turning off ADP resolved it. So I think a hint that this may be caused by ADP would be good.

**Comment by boredazfcuk** [comment]
I often run into this issue and I don't have ADP enabled.

For me, the process is due to running icloud-photos-downloader over and over and over again (deleting/recreating containers while testing). I believe it's because it logs in every time the utility is run, rather than re-using an existing session. This repetition of the login process is what triggers the temporary ban from Apple.

Leaving the container overnight fixed the issue. It would be nice if icloud-photos-downloader could re-use existing connections between uses, by saving, detecting and attempting to reuse session data.

But yeah, this issue can have multiple root causes. It's not just ADP related.

**Comment by LukePeltier** [comment]
There is a new setting that i had to enable in icloud called "Access iCloud Data on the Web" 

![Image](https://github.com/user-attachments/assets/223f6d1c-cd04-4957-9d4c-2144725e90ae)

Settings > Apple Account > iCloud

**Comment by iCosiSenpai** [comment]
Same `private db access disabled (ACCESS_DENIED)` error, the issue is still open so I can confirm it happens today (2026-06-02) as well.

Setup:
- `icloudpd/icloudpd:1.32.3` in Docker
- Login + 2FA completed successfully yesterday
- **ADP disabled**
- "Access iCloud Data on the Web" enabled in iCloud settings
- Container left running, automatic retries every 3600s

After ~22h the throttle is still active. Auth works correctly (cookies renewed, 200 response from `setup.icloud.com` with valid `dsInfo`); only access to the Photos Private DB stays blocked.

Adding one operational detail: this morning the container had exited with code 1. On `docker start` it retried the request immediately, without waiting the additional 3600s. Not sure if this can worsen the throttle or if Apple only counts total time since last login.
