### ISSUE TITLE
Photos don't get deleted, even with --delete-after-download

### ISSUE THREAD

**Issue by dojoca** [icloud-photos-downloader/icloud_photos_downloader#1027]
## Overview
I've run "sudo icloudpd -u "your-email@example.com" -p "your-password" -d '/your/download/path' --delete-after-download"
I have previously authenticated. 

The output is this:
[sudo] password for server: 
2024-12-27 12:19:08 DEBUG    Authenticating...
2024-12-27 12:19:11 DEBUG    Looking up all photos and videos from album All Photos...
2024-12-27 12:19:12 INFO     Downloading 24740 original photos and videos to /your/download/path ...
2024-12-27 12:19:15 DEBUG    Downloading /your/download/path/2024/10/20/IMG_0247.HEIC...
2024-12-27 12:19:16 INFO     Downloaded /your/download/path/2024/10/20/IMG_0247.HEIC
2024-12-27 12:19:16 DEBUG    Deleting IMG_0247.HEIC in iCloud...
2024-12-27 12:19:16 DEBUG    POST https://icloud-database-url {"atomic": true, "desiredKeys": ["isDeleted"], "operations": [{"operationType": "update", "record": {"fields": {"isDeleted": {"value": 1}}, "recordChangeTag": "2qj5", "recordName": "record-unique-id", "recordType": "CPLAsset"}}], "zoneID": {"zoneName": "PrimarySync", "ownerRecordName": "owner-unique-id", "zoneType": "REGULAR_CUSTOM_ZONE"}}
2024-12-27 12:19:17 DEBUG    {'Server': 'AppleHttpServer', 'Date': 'Fri, 27 Dec 2024 04:19:17 GMT', 'Content-Type': 'application/json; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Responding-Instance': 'instance-details', 'Set-Cookie': 'X-APPLE-WEBAUTH-TOKEN=...;Secure;HttpOnly', 'Access-Control-Allow-Origin': 'https://www.icloud.com', 'Access-Control-Allow-Credentials': 'true', 'Timing-Allow-Origin': 'https://www.icloud.com', 'X-Apple-CloudKit-Version': '1.0', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains;', 'x-apple-user-partition': '175', 'via': 'cloud-details', 'X-Apple-Request-UUID': 'request-uuid', 'access-control-expose-headers': 'X-Apple-Request-UUID,X-Responding-Instance,Via', 'X-Apple-Edge-Response-Time': '496'}
2024-12-27 12:19:17 DEBUG    {'records': [{'recordName': 'record-unique-id', 'recordType': 'CPLAsset', 'fields': {'isDeleted': {'value': 1, 'type': 'INT64'}}, 'pluginFields': {}, 'recordChangeTag': '2zqp', 'created': {'timestamp': 1733362900758, 'userRecordName': 'user-unique-id', 'deviceID': 'device-id'}, 'modified': {'timestamp': 1735273156947, 'userRecordName': 'user-unique-id', 'deviceID': 'device-id'}, 'deleted': False, 'expirationTime': 1738729156}], 'syncToken': 'sync-token'}
2024-12-27 12:19:17 INFO     Deleted IMG_0247.HEIC in iCloud
2024-12-27 12:19:17 DEBUG    Downloading /your/download/path/2024/10/20/IMG_0246.HEIC...
  0%|                                                                                                      | 1/24740 [00:05<34:30:53,  5.02s/it]

I then hit CTRL+C (since the error above showed up) and get this:

Aborted!
Traceback (most recent call last):                                                                                                              
  File "/usr/local/bin/icloudpd", line 5, in <module>
    from icloudpd import __main__
  File "/usr/local/lib/python3.10/dist-packages/icloudpd/__main__.py", line 5, in <module>
    sys.exit(subprocess.call([os.path.join(os.path.dirname(__file__), "icloudpd"), *sys.argv[1:]]))
  File "/usr/lib/python3.10/subprocess.py", line 347, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. Version of the app, OS/System, and minimum command line to reproduce. )
1. sudo icloudpd -u "your-email@example.com" -p "your-password" -d '/your/download/path' --delete-after-download

## Expected Behavior
It should download then delete the photos from iCloud.

## Actual Behavior
The error above happens, photos don't get downloaded then deleted.

## Context
It's a pain in the bum to manually delete photos from iCloud. 

Also - just to be clear, I have tried this with iCloud in the normal (syncing) mode and in the "photos will be deleted in 30 days" mode. 

No idea why this isn't working?

**Comment by AndreyNikiforov** [comment]
What version of icloudpd are you using and where did you obtain it? Debugging requests in your output seems not matching parameters.

**Comment by dojoca** [comment]
Hi Andrey - thanks for the quick reply and seasons greetings :)

This is the --version information:
version:1.25.0, commit sha:96f9451, commit timestamp:Wed Dec  4 01:01:43 2024 AWST

as far as I am aware, I've installed icloudpd from this github.

**Comment by dojoca** [comment]
Just realised - is it possible the debugging request on my output isn't working because I ran it through chatGPT to remove identifying information?

**Comment by AndreyNikiforov** [comment]
> Just realised - is it possible the debugging request on my output isn't working because I ran it through chatGPT to remove identifying information?

The strange part for me was that your log shows `2024-12-27 12:19:16 DEBUG POST...` - that should not be displayed unless extra logging is enabled. I tested latest version and it indeed shows log for deleting request - something to clean up.

I tried to reproduce your issue on my test account and image was successfully deleted in iCloud after downloading - `icloudpd` behaved as expected on my account.

**Comment by dojoca** [comment]
Hi Andrey,

I've tried to run icloudpd with the --delete-after-download setting on a fresh(ish) Ubuntu 24.04 system. I installed icloudpd using pip/pipx. 

it's weirdly giving me the same error. 

The only "unusual" thing is that my iCloud is currently full, so new photos aren't syncing. 

> icloudpd -u "email@gmail.com" -d '/home/name/Pictures/dcphotos' --delete-after-download
> 2025-01-03 10:20:51 DEBUG    Authenticating...
> 2025-01-03 10:20:54 DEBUG    Looking up all photos and videos from album All Photos...
> 2025-01-03 10:20:55 INFO     Downloading 25720 original photos and videos to /home/name/Pictures/dcphotos ...          
> 2025-01-03 10:20:57 DEBUG    Downloading /home/name/Pictures/dcphotos/2024/12/27/IMG_0450.HEIC...                      
> 2025-01-03 10:20:59 INFO     Downloaded /home/name/Pictures/dcphotos/2024/12/27/IMG_0450.HEIC                          
> 2025-01-03 10:20:59 DEBUG    Deleting IMG_0450.HEIC in iCloud...                                                          
> 2025-01-03 10:20:59 DEBUG    POST https://p175-ckdatabasews.icloud.com:443/database/1/com.apple.photos.cloud/production/private/records/modify?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&ckjsBuildVersion=17DProjectDev77&ckjsVersion=2.0.5&clientId=auth-09a990a6-c979-11ef-9aa4-30de4b6755d2&dsid=1269469938&remapEnums=True&getCurrentSyncToken=True {"atomic": true, "desiredKeys": ["isDeleted"], "operations": [{"operationType": "update", "record": {"fields": {"isDeleted": {"value": 1}}, "recordChangeTag": "32g6", "recordName": "5576D724-AD26-418E-95EF-D09F1FDD5D42", "recordType": "CPLAsset"}}], "zoneID": {"zoneName": "PrimarySync", "ownerRecordName": "_66f90cda044d5f4189b10fcf2cd0edb9", "zoneType": "REGULAR_CUSTOM_ZONE"}}
> 2025-01-03 10:20:59 DEBUG    {'Server': 'AppleHttpServer/d2dcc6a0a5e3', 'Date': 'Fri, 03 Jan 2025 02:20:59 GMT', 'Content-Type': 'application/json; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Responding-Instance': 'ckdatabasews:1694961812:prod-p175-ckdatabasews-100percent-5bbcbfc46-bj26w:8080:2429B399:feb23af4ba8edac43c48e1a1025eba9548907ffd', 'Set-Cookie': 'X-APPLE-WEBAUTH-TOKEN="v=2:t=FA==BST_IAAAAAAABLwIAAAAAGd3SYsRDmdzLmljbG91ZC5hdXRovQDgYbY3lQdsWtRsBBVE8W9KCg7jzDxEIL3A8dKeq-ZxmIoaG0JZkb3lGZ8tBg6nqtSD8fLfTFH67oe-wD4UiARTs7Zp85GrDvsSsSq44DLMcvECW7sT729_ouUnYRvkKzgMNYikvzrC3LuhlQOOoU9yMlgFoQ~~";Expires=Sun, 2-Feb-2025 02:20:59 GMT;Path=/;Domain=.icloud.com;Secure;HttpOnly', 'Access-Control-Allow-Origin': 'https://www.icloud.com', 'Access-Control-Allow-Credentials': 'true', 'Timing-Allow-Origin': 'https://www.icloud.com', 'X-Apple-CloudKit-Version': '1.0', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains;', 'x-apple-user-partition': '175', 'via': 'xrail:icloud-xrail-group175-ext-6569c87997-vdp7b:8301:24R623:grp175,631194250daa17e24277dea86cf30319:796f81aa679a5ccd79fcdd7b950868e2:ausyd2', 'X-Apple-Request-UUID': '69c9141b-bd13-41e4-b8e6-265b932fe959', 'access-control-expose-headers': 'X-Apple-Request-UUID,X-Responding-Instance,Via', 'X-Apple-Edge-Response-Time': '576'}
> 2025-01-03 10:20:59 DEBUG    {'records': [{'recordName': '5576D724-AD26-418E-95EF-D09F1FDD5D42', 'recordType': 'CPLAsset', 'fields': {'isDeleted': {'value': 1, 'type': 'INT64'}}, 'pluginFields': {}, 'recordChangeTag': '32lb', 'created': {'timestamp': 1735303314391, 'userRecordName': '_66f90cda044d5f4189b10fcf2cd0edb9', 'deviceID': '7261D16F4C1BE8BAD1FCF3C800481DAB65B94CA05DF2CE26C67689A14669C7D2'}, 'modified': {'timestamp': 1735870859332, 'userRecordName': '_66f90cda044d5f4189b10fcf2cd0edb9', 'deviceID': '2'}, 'deleted': False, 'expirationTime': 1739326859}], 'syncToken': 'HwoECOTfCBgAIhYIs4T5re+6hrKJARC6iMim/N27sL4BKAA='}
> 2025-01-03 10:20:59 INFO     Deleted IMG_0450.HEIC in iCloud 
> 


Other information:
- OS version is Ubuntu 24.04
- I installed icloudpd using 'pipx install icloudpd'


Is there anything else I could try? I think I've eliminated my computer as the issue (as this is on an entirely different computer).

**Comment by dojoca** [comment]
Anyone else encountering this problem?

**Comment by AndreyNikiforov** [comment]
> **Edited to add - the photos are being deleted (moved to the "Recently Deleted" folder), so I guess the question is - is the error/message below somthing to be concerned about?**
> 

Debug with POST request is not an error and is not affecting behavior.

> **Second edit: not all photos got deleted. Seems to have like a 50% success rate.**

I don't know why half of your assets are not removed. `--delete-after-download` acts only after downloading. If the asset is already in the local storage, then it won't be deleted in the iCloud. That behavior should not be the cause of you low success rate however, because I cannot imaging `icloudpd` failing for every other download and your restarting it.

> The only "unusual" thing is that my iCloud is currently full, so new photos aren't syncing.

I don't know how Apple iCloud behaves in such cases. Since you already deleted some assets (50% success rate from above), then you should have some space. Alternatively, you can consider temporally upgrading iCloud account.

**Comment by dojoca** [comment]
Well spotted - I didn't notice at first that it seems to only download 50% of the files. 

I decided to try use a script of some sort - I will admit, I did not write this script because it was AI generated. I didn't expect it to work but it did... and encountered the same issue, which means it's not icloudpd. 

What a bizarre problem. 

I'm just leaving this script here in case it's helpful - it's got the added benefit of downloading and deleting all files, except for those from the last 30 days:

`import os
import sys
from pyicloud import PyiCloudService
from datetime import datetime, timedelta
import click
from tqdm import tqdm

@click.command()
@click.option('--email', prompt='iCloud email', help='Your iCloud email address')
@click.option('--password', prompt=True, hide_input=True, help='Your iCloud password')
@click.option('--output-dir', default='photos', help='Directory to save photos to')
@click.option('--delete/--no-delete', default=False, help='Delete photos older than 30 days after download')
@click.option('--days-to-keep', default=30, help='Number of days of recent photos to keep')
def download_photos(email, password, output_dir, delete, days_to_keep):
    """Download all photos from iCloud and optionally delete those older than specified days."""
    try:
        # Login to iCloud
        api = PyiCloudService(email, password)
        
        # Handle 2FA if needed
        if api.requires_2fa:
            print("Two-factor authentication required.")
            code = input("Enter the code you received: ")
            result = api.validate_2fa_code(code)
            if not result:
                print("Failed to verify 2FA code")
                return

        # Create output directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)

        # Calculate cutoff date (make it timezone-aware)
        cutoff_date = datetime.now().astimezone() - timedelta(days=days_to_keep)
        
        # Get all photos
        print("Fetching photo list...")
        photos = api.photos.all
        total = len(photos)
        print(f"Found {total} photos")

        # Counters for summary
        downloaded = 0
        skipped_existing = 0
        kept_recent = 0
        deleted = 0
        errors = 0

        # Download each photo
        for photo in tqdm(photos, desc="Processing photos"):
            # Generate filename with date and original filename
            created = photo.created
            created_str = created.strftime('%Y%m%d_%H%M%S')
            filename = f"{created_str}_{photo.filename}"
            path = os.path.join(output_dir, filename)

            try:
                # Skip if file already exists
                if os.path.exists(path):
                    print(f"Skipping {filename} (already exists)")
                    skipped_existing += 1
                    continue

                # Download the photo
                download = photo.download()
                with open(path, 'wb') as file:
                    file.write(download.raw.read())
                downloaded += 1

                # Check if photo should be deleted
                if delete and created < cutoff_date:
                    photo.delete()
                    deleted += 1
                    print(f"Deleted {filename} from iCloud (older than {days_to_keep} days)")
                else:
                    kept_recent += 1

            except Exception as e:
                print(f"Error processing {filename}: {str(e)}")
                errors += 1

        # Print summary
        print("\nDownload Summary:")
        print(f"Total photos found: {total}")
        print(f"Successfully downloaded: {downloaded}")
        print(f"Skipped (already exists): {skipped_existing}")
        print(f"Kept in iCloud (recent): {kept_recent}")
        if delete:
            print(f"Deleted from iCloud: {deleted}")
        if errors:
            print(f"Errors encountered: {errors}")
        print(f"\nPhotos saved to: {os.path.abspath(output_dir)}")

    except Exception as e:
        print(f"Error: {str(e)}")
        sys.exit(1)

if __name__ == '__main__':
    download_photos()`

I'm re-running this script this morning, as it downloaded 50% of the remaining ~$12k photos. Hopefully it'll eventually just download all of them. The summary at the end was this - which is strange, since it says it finds all the photos, only downloads half, but lists no errors. 

`Download Summary:
Total photos found: 12820
Successfully downloaded: 6422
Skipped (already exists): 0
Kept in iCloud (recent): 0
Deleted from iCloud: 6397
Errors encountered: 25
`
Anyway - thanks for the help :)
