### ISSUE TITLE
struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by carrazy** [icloud-photos-downloader/icloud_photos_downloader#113]
I'm trying to download a very large library (171,361) and am consistently getting this error. Below is the results that come back at the time of the error. Any idea how to resolve it?

Photos/2014/03/29/IMG_5137.JPG already exists.:  22%|############4                                           | 38218/171361 [17:39<53:55, 41.16it/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/icloudpd", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/icloudpd/base.py", line 396, in main
    if not exif_datetime.get_photo_exif(download_path):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/icloudpd/exif_datetime.py", line 11, in get_photo_exif
    exif_dict = piexif.load(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/piexif/_load.py", line 38, in load
    exif_dict["0th"] = exifReader.get_ifd_dict(pointer, "0th")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/piexif/_load.py", line 99, in get_ifd_dict
    self.tiftag[pointer: pointer+2])[0]
struct.error: unpack requires a buffer of 2 bytes

**Comment by carrazy** [comment]
I think I partially solved my issue. I had been running it with the --set-exif-datetime option. This is likely what was failing. I ran it again without that option and it made it past the file(s) that were failing. In the future, it would be nice to be able to see what file it failed on so it could be fixed manually.

**Comment by menkej** [comment]
Hi @carrazy !
Could you please recheck if this issue still occurs with the current version?

Thanks, Jörg

**Comment by carrazy** [comment]
I haven't used icloudpd for a while and thought I would give it another try. I am still getting some errors (ioerror disk space and  thread exception) when using the --set-exif-datetime option, but it doesn't cause the process to hang. I don't get any errors when I try it again without option enabled. 

Below is the thread exception error:

2020-10-06 13:37:04 DEBUG    Setting EXIF timestamp for /Volumes/Lacie4TB/icloudpd_old/Photos/2005/05/15/MBap84-1161952.jpg: 2005:05:15 23:01:41
Exception in thread Thread-71:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/icloudpd/base.py", line 567, in worker
    download_photo(counter, item)
  File "/usr/local/lib/python3.8/site-packages/icloudpd/base.py", line 490, in download_photo
    not exif_datetime.get_photo_exif(download_path):
  File "/usr/local/lib/python3.8/site-packages/icloudpd/exif_datetime.py", line 11, in get_photo_exif
    exif_dict = piexif.load(path)
  File "/usr/local/lib/python3.8/site-packages/piexif/_load.py", line 53, in load
    exif_dict["1st"] = exifReader.get_ifd_dict(pointer, "1st")
  File "/usr/local/lib/python3.8/site-packages/piexif/_load.py", line 108, in get_ifd_dict
    tag_count = struct.unpack(self.endian_mark + "H",
struct.error: unpack requires a buffer of 2 bytes

**Comment by menkej** [comment]
This is really strange @carrazy... I tried a while to reproduce it with the current version. Are you still hitting this with the current version? If this is the case: does it also happen if you use --threads-num 1?

**Comment by carrazy** [comment]
Jörg,

Thank you for checking back. I just tried it again with the same options after updating to 1.6.2 and didn't get any errors! I'm hoping something in the 1.6.2 fixed it.

Thank you!

**Comment by menkej** [comment]
Excellent. The current implementation of multithreading has some issues and will be removed because of that. We did not really see much of a speed gain anyways from it. So for now: use --threads-num 1 (current default now) and you should be safe. losing this issue for now. Feel free to reopen if it happens again.
