### ISSUE TITLE
Error saving to keyring

### ISSUE THREAD

**Issue by johnluber** [icloud-photos-downloader/icloud_photos_downloader#127]
I'm running the latest Mojave and when trying to save the iCloud password to the keyring I get:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keyring/backends/OS_X.py", line 83, in set_password
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/icloud", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyicloud_ipd/utils.py", line 56, in store_password_in_keyring
    password,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keyring/backends/OS_X.py", line 85, in set_password
    raise PasswordSetError("Can't store password in keychain")
keyring.errors.PasswordSetError: Can't store password in keychain

Any idea how to fix this?

**Comment by menkej** [comment]
Hi @johnluber !
Thanks for your PR and sorry for the delay. Are you still experiencing this issue with the latest version?

**Comment by menkej** [comment]
As there was no response for a month I close this issue. Feel free to reopen with additional information if the issue still exists.

**Comment by petebocken** [comment]
I believe I'm having the same or similar error:

```
Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.8/site-packages/keyring/backends/OS_X.py", line 83, in set_password
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/opt/homebrew/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/opt/homebrew/lib/python3.8/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/opt/homebrew/lib/python3.8/site-packages/keyring/backends/OS_X.py", line 85, in set_password
    raise PasswordSetError("Can't store password in keychain")
keyring.errors.PasswordSetError: Can't store password in keychain
```

I was able to run the script once successfully. It created the cookie file in `~/.pyicloud` and it's populated with the cookie file. However, if I try to run the command while including `--cookie-directory` it gives the above error.

**Comment by johnluber** [comment]
I did. The solution for me was to move to an Ubuntu vm. Sent from my iPhoneOn Oct 6, 2022, at 8:26 AM, petebocken ***@***.***> wrote:﻿
@johnluber Did you ever get this working? What was the issue? I think I'm having the same issue with python 3.10 and current version of icloudpd.
