### ISSUE TITLE
iCloud Photo Library not finished  indexing.  Please try again in a few minutes       

### ISSUE THREAD

**Issue by duryding** [icloud-photos-downloader/icloud_photos_downloader#138]
When I run the script for the first time, I get blow massage. 
1 hour 2 hour and second day also like this.

```
2019-05-25 00:04:40 DEBUG    Authenticating...                                               
2019-05-25 00:04:43 DEBUG    Looking up all photos and videos...                             
Traceback (most recent call last):                                                           
  File "/usr/bin/icloudpd", line 11, in <module>                                             
    sys.exit(main())                                                                         
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__               
    return self.main(*args, **kwargs)                                                        
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main                   
    rv = self.invoke(ctx)                                                                    
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke                 
    return ctx.invoke(self.callback, **ctx.params)                                           
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke                 
    return callback(*args, **kwargs)                                                         
  File "/usr/lib/python3.6/site-packages/icloudpd/base.py", line 253, in main                
    photos = icloud.photos.all                                                               
  File "/usr/lib/python3.6/site-packages/pyicloud_ipd/base.py", line 332, in photos          
    self.params                                                                              
  File "/usr/lib/python3.6/site-packages/pyicloud_ipd/services/photos.py", line 167, in __ini
t__                                                                                          
    'again in a few minutes'), None)                                                         
pyicloud_ipd.exceptions.PyiCloudServiceNotActivatedErrror: iCloud Photo Library not finished 
indexing.  Please try again in a few minutes       
```

**Comment by menkej** [comment]
> iCloud Photo Library not finished 

It seems like iCloud was indexing for some reason. Does the error persist? Can it be that you just started using iCloud Photo Library recently?

**Comment by menkej** [comment]
Closing because there was no reaction of the ticket submitter.
