### ISSUE TITLE
Authentication (2FA) fails

### ISSUE THREAD

**Issue by adpalm** [icloud-photos-downloader/icloud_photos_downloader#142]
At some point the authentication broke. I've tried deleting the cookie .pyicloud/ but to no avail. Anyone else experiencing this?

root@Brage:~# icloudpd --version
icloudpd, version 1.4.4

root@Brage:~# icloudpd 
iCloud username/email: ----CENSORED---
2019-08-09 13:14:43 DEBUG    Authenticating...
iCloud Password: 
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icloudpd/base.py", line 243, in main
    client_id=os.environ.get("CLIENT_ID"),
  File "/usr/local/lib/python2.7/dist-packages/icloudpd/authentication.py", line 39, in authenticate
    client_id=client_id)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError(u'Failed to validate the credentials from cookie',))

**Comment by 4gra** [comment]
Have you updated to the latest https://github.com/picklepete/pyicloud/tree/master/pyicloud ?  See the ongoing issues against that library.

**Comment by octplane** [comment]
@adpalm Are you still having the issue with the latest version of the app?

**Comment by menkej** [comment]
Hi @adpalm !
You are using an older version. Can you please recheck with the current version (running on python 3)?

Thanks,
Jörg

**Comment by menkej** [comment]
no reaction after almost 30 days, so I assume this is no longer the case. If you are still having this issue with the current version of the app feel free to reopen with updated information, @adpalm . Thanks!
