### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by jiang123574** [icloud-photos-downloader/icloud_photos_downloader#148]
2020-05-08 01:46:14 DEBUG    Authenticating...                                                                                           
Traceback (most recent call last):                                                                                                       
  File "/usr/local/bin/icloudpd", line 11, in <module>                                                                                   
    sys.exit(main())                                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__                                                     
    return self.main(*args, **kwargs)                                                                                                    
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main                                                         
    rv = self.invoke(ctx)                                                                                                                
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke                                                       
    return ctx.invoke(self.callback, **ctx.params)                                                                                       
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke                                                       
    return callback(*args, **kwargs)                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/icloudpd/base.py", line 292, in main                                                      
    directory = os.path.normpath(directory)                                                                                              
  File "/usr/lib/python3.6/posixpath.py", line 340, in normpath                                                                          
    path = os.fspath(path)                                                                                                               
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by duraki** [comment]
@ndbroadbent same here. @jiang123574 how did you fix it?

**Comment by ZorvyY** [comment]
This was a pretty simple error but I might as well explain what happened for the next person. I got the error because I didn't pass the `--directory` argument.

**Comment by metahnetoutage** [comment]
Yes I know that. This is why I did not want to bother fixing this or
rebuilding it. I rather work on a solution from scratch that just works!

Dima

**Comment by menkej** [comment]
--directory is mandatory if not --list-albums. The error-handling aka click dependency should be improved.

**Comment by AndreyNikiforov** [comment]
Closing at it was addresses in 1.6.2 release. Feel free to reopen if problem persists.
