### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudServiceNotActivatedErrror: Please log into https://icloud.com/ to manually  finish setting up your iCloud service (ZONE_NOT_FOUND) 

### ISSUE THREAD

**Issue by JoshuaChou2018** [icloud-photos-downloader/icloud_photos_downloader#151]
2020-05-21 06:30:02 DEBUG    Authenticating...                                                            
Traceback (most recent call last):                                                                        
  File "/usr/local/bin/icloudpd", line 10, in <module>                                                    
    sys.exit(main())                                                                                      
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 722, in __call__                      
    return self.main(*args, **kwargs)                                                                     
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 697, in main                          
    rv = self.invoke(ctx)                                                                                 
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 895, in invoke                        
    return ctx.invoke(self.callback, **ctx.params)                                                        
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 535, in invoke                        
    return callback(*args, **kwargs)                                                                      
  File "/usr/local/lib/python3.7/dist-packages/icloudpd/base.py", line 276, in main                       
    photos = icloud.photos.albums[album]                                                                  
  File "/usr/local/lib/python3.7/dist-packages/pyicloud_ipd/base.py", line 332, in photos                 
    self.params                                                                                           
  File "/usr/local/lib/python3.7/dist-packages/pyicloud_ipd/services/photos.py", line 160, in __init__    
    headers={'Content-type': 'text/plain'}                                                                
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 578, in post                   
    return self.request('POST', url, data=data, json=json, **kwargs)                                      
  File "/usr/local/lib/python3.7/dist-packages/pyicloud_ipd/base.py", line 100, in request                
    self._raise_error(code, reason)                                                                       
  File "/usr/local/lib/python3.7/dist-packages/pyicloud_ipd/base.py", line 114, in _raise_error           
    raise(api_error)                                                                                      
pyicloud_ipd.exceptions.PyiCloudServiceNotActivatedErrror: Please log into https://icloud.com/ to manually
 finish setting up your iCloud service (ZONE_NOT_FOUND)

**Comment by menkej** [comment]
this exception should be catcht correctly and give the user a better error message/information what to do.

**Comment by dmd** [comment]
So... what should I do? This is what I get when I attempt to use icloudpd.

**Comment by dmd** [comment]
(And I [do have sync turned on](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/107#issuecomment-791494091).)
