### ISSUE TITLE
OverflowError when downloading photo

### ISSUE THREAD

**Issue by ian-mcdowell** [icloud-photos-downloader/icloud_photos_downloader#243]
I'm unable to successfully run the script. It logs a bunch of photo names from 2020 back until 2015, then crashes with an error. There must be a photo in my library with a created at date that is invalid in some way.

```
...
/home/user/iCloud/2015/06/11/2015_06_11_183510.jpg
/home/user/iCloud/2015/06/11/2015_06_11_183503.jpg
/home/user/iCloud/2015/06/11/2015_06_11_181757.jpg
/home/user/iCloud/2015/06/11/2015_06_11_181457.jpg
Traceback (most recent call last):
File "/usr/bin/icloudpd", line 11, in <module>
load_entry_point('icloudpd==1.7.0', 'console_scripts', 'icloudpd')()
File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.0-py3.8.egg/icloudpd/base.py", line 562, in main
File "/usr/lib/python3.8/site-packages/icloudpd-1.7.0-py3.8.egg/icloudpd/base.py", line 380, in download_photo
File "/usr/lib/python3.8/site-packages/pytz/tzinfo.py", line 201, in fromutc
return (dt + inf[0]).replace(tzinfo=self._tzinfos[inf])
OverflowError: date value out of range
```

**Comment by menkej** [comment]
What are the exact options you're using to run the script?

**Comment by IMcD23** [comment]
I'm running this in the latest build of the docker container from [docker-icloudpd](https://github.com/boredazfcuk/docker-icloudpd). 

Here are the logs from the top of the container's output:
```
2020-11-28 05:33:53 INFO ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2020-11-28 05:33:53 INFO ***** /usr/local/bin/sync-icloud.sh script version: 2020/11/21_15:10 *****

2020-11-28 05:33:53 INFO Alpine Linux v3.12
2020-11-28 05:33:53 INFO Python version: 3.8.5

2020-11-28 05:33:53 INFO icloudpd version: 1.7.0

2020-11-28 05:33:56 INFO pyicloud-ipd version: 0.10.1

2020-11-28 05:33:58 INFO Interactive session: False
2020-11-28 05:33:58 INFO Local user: user:1000
2020-11-28 05:33:58 INFO Local group: group:1000
2020-11-28 05:33:58 INFO Force GID: False
2020-11-28 05:33:58 INFO LAN IP Address: 172.20.0.12
2020-11-28 05:33:58 INFO Apple ID: <my_username>
2020-11-28 05:33:58 INFO Apple ID password: usekeyring
2020-11-28 05:33:58 INFO Authentication Type: 2FA
2020-11-28 05:33:58 INFO Cookie path: /config/myusername
2020-11-28 05:33:58 INFO Cookie expiry notification period: 7
2020-11-28 05:33:58 INFO Download destination directory: /home/user/iCloud
2020-11-28 05:33:58 INFO Folder structure: {:%Y/%m/%d}
2020-11-28 05:33:58 INFO Directory permissions: 777
2020-11-28 05:33:58 INFO File permissions: 666
2020-11-28 05:33:58 INFO Synchronisation interval: 86400
2020-11-28 05:33:58 INFO Synchronisation delay (minutes): 0
2020-11-28 05:33:58 INFO Time zone: America/Los_Angeles
2020-11-28 05:33:58 INFO Set EXIF date/time: False
2020-11-28 05:33:58 INFO Auto delete: False
2020-11-28 05:33:58 INFO Photo size: original
2020-11-28 05:33:58 INFO Skip live photos: False
2020-11-28 05:33:58 INFO Number of most recently added photos to download: Download All Photos
2020-11-28 05:33:58 INFO Live photo size: original
2020-11-28 05:33:58 INFO Skip videos False
2020-11-28 05:33:58 WARNING Additional command line options is depreceated. Please specify all options using the dedicated variables: --recent 500

2020-11-28 05:33:58 INFO Convert HEIC to JPEG: False
2020-11-28 05:33:58 INFO Group, group:1000, already created
2020-11-28 05:33:58 INFO User, user:1000, already created
2020-11-28 05:33:58 INFO Correct owner on config directory, if required
2020-11-28 05:33:58 INFO Correct group on config directory, if required
2020-11-28 05:33:58 INFO Using password stored in keyring
2020-11-28 05:33:58 INFO Check download directory mounted correctly
2020-11-28 05:33:58 INFO Failsafe file /home/user/iCloud/.mounted exists
2020-11-28 05:33:58 INFO Set owner, user, on iCloud directory, if required
2020-11-28 05:33:58 INFO Set group, group, on iCloud directory, if required
2020-11-28 05:33:58 INFO Correct owner on icloudpd temp directory, if required
2020-11-28 05:33:58 INFO Correct group on icloudpd temp directory, if required
2020-11-28 05:33:58 INFO Correct owner on config directory, if required
2020-11-28 05:33:58 INFO Correct group on config directory, if required
2020-11-28 05:33:58 INFO Correct owner on keyring directory, if required
2020-11-28 05:33:58 INFO Correct group on keyring directory, if required
2020-11-28 05:33:58 INFO Set 777 permissions on iCloud directories, if required
2020-11-28 05:33:58 INFO Set 666 permissions on iCloud files, if required
2020-11-28 05:33:58 INFO Command line options: --directory /home/user/iCloud --cookie-directory /config --folder-structure {:%Y/%m/%d} --username <my_username>
2020-11-28 05:33:58 INFO Sync user user
2020-11-28 05:33:58 INFO Check 2FA Cookie
2020-11-28 05:33:58 INFO Cookie exists, check expiry date
2020-11-28 05:33:58 INFO Valid two factor authentication cookie found. Days until expiration: 90
2020-11-28 05:33:58 INFO Check download directory mounted correctly
2020-11-28 05:33:58 INFO Failsafe file /home/user/iCloud/.mounted exists
2020-11-28 05:33:58 INFO Check for new files using password stored in keyring...
/home/user/iCloud/2020/11/25/IMG_0343.HEIC
...
```

**Comment by menkej** [comment]
Hi Ian,
you're using a 3rd party container image provided by @boredazfcuk. The project can be found here: https://github.com/boredazfcuk/docker-icloudpd

I'm not sure if this might come from something in the container image. But I assume your idea of a somehow corrupt photo might be valid. The error happens in a 3rd party lib that tries to convert the date given in the iCloud response.

Is it always happening with the same image? Have you tried the same with a direct installation of the script from this project - not using the docker container? Can you possibly check around the following time 2015_06_11_181457 in Photos app if you notice something "strange"?

cheers
Jörg

**Comment by boredazfcuk** [comment]
I've just pushed an updated image to Dockerhub of my container. It now includes a new line in the log to show the exact command used to launch icloudpd e.g.:
```
2020-11-28 17:04:21 INFO     iCloudPD launch command: /usr/bin/icloudpd --directory /home/user/iCloud --cookie-directory /config --folder-structure {:%Y/%m} --username user@notmyemail.com --set-exif-datetime --auto-delete  2>&1
```

**Comment by IMcD23** [comment]
I checked my Photos app and don't notice anything strange. There is regular content before and after that time. 

I just modified the script to print the created date of each photo, then ran:
`icloudpd --directory /home/user/iCloud/ --username <my_email> --cookie-directory /config --folder-structure {:%Y/%m/%d} --only-print-filenames --threads-num 8`

Based on the output, there's a photo in my library with a very old date.
```
2020-11-29 01:22:42 INFO     Photo created date: 2015-06-11 23:35:03+00:00
/home/user/iCloud/2015/06/11/2015_06_11_183503.jpg
2020-11-29 01:22:42 INFO     Photo created date: 2015-06-11 23:17:57+00:00
/home/user/iCloud/2015/06/11/2015_06_11_181757.jpg
2020-11-29 01:22:42 INFO     Photo created date: 2015-06-11 23:14:57+00:00
/home/user/iCloud/2015/06/11/2015_06_11_181457.jpg
2020-11-29 01:22:42 INFO     Photo created date: 0001-01-01 06:54:27+00:00
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    load_entry_point('icloudpd==1.7.1', 'console_scripts', 'icloudpd')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.1-py3.8.egg/icloudpd/base.py", line 560, in main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.8/site-packages/icloudpd-1.7.1-py3.8.egg/icloudpd/base.py", line 378, in download_photo
    created_date = photo.created.astimezone(get_localzone())
  File "/usr/lib/python3.8/site-packages/pytz/tzinfo.py", line 201, in fromutc
    return (dt + inf[0]).replace(tzinfo=self._tzinfos[inf])
OverflowError: date value out of range
```

**Comment by menkej** [comment]
Probably the best solution would be to just catch/print/continue...

**Comment by IMcD23** [comment]
That's what I was thinking as well. I made that change locally and tested it out, and the script finished successfully.

**Comment by menkej** [comment]
Excellent! Do you want to submit a pull request? Otherwise I'd do this change for you.

**Comment by IMcD23** [comment]
Done. PR #245
