### ISSUE TITLE
Keyring issue - cannot authenticate

### ISSUE THREAD

**Issue by yankkii** [icloud-photos-downloader/icloud_photos_downloader#257]
Hi all,

when trying to use icloud to authenticate I'm getting following error:

> > ubuntu@ubuntu:~/icloud_photos_downloader$ icloud --username yankes@cudowny.net
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/secretstorage/util.py", line 31, in function_out
>     return function_in(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
>     return self._connection.call_blocking(self._named_service,
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
>     reply_message = self.send_message_with_reply_and_block(
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/secrets/collection/login
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 155, in get_default_collection
>     return Collection(bus)
>   File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 42, in __init__
>     self.collection_props_iface.Get(COLLECTION_IFACE, 'Label',
>   File "/usr/lib/python3/dist-packages/secretstorage/util.py", line 34, in function_out
>     raise ItemNotFoundException('Item does not exist!')
> secretstorage.exceptions.ItemNotFoundException: Item does not exist!
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 39, in get_default_collection
>     collection = secretstorage.get_default_collection(bus)
>   File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 157, in get_default_collection
>     return create_collection(bus, 'Default',
>   File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 139, in create_collection
>     raise ItemNotFoundException('Prompt dismissed.')
> secretstorage.exceptions.ItemNotFoundException: Prompt dismissed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/bin/icloud", line 8, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 191, in main
>     password = utils.get_password(
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 13, in get_password
>     return get_password_from_keyring(username)
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 35, in get_password_from_keyring
>     result = keyring.get_password(
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/keyring/core.py", line 42, in get_password
>     return _keyring_backend.get_password(service_name, username)
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 51, in get_password
>     collection = self.get_default_collection()
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 41, in get_default_collection
>     raise InitError("Failed to create the collection: %s." % e)
> keyring.errors.InitError: Failed to create the collection: Prompt dismissed..

What could be wrong here? Please help me 

Maciej

**Comment by boredazfcuk** [comment]
Do you have the Python packages `keyrings.alt` and `keyring` installed?
```
pip3 install keyrings.alt keyring
```

**Comment by yankkii** [comment]
Yeah, I did. Also uninstall - install again. And tried to change version becasue of:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> pyicloud-ipd 0.10.1 requires keyring<9.0,>=8.0, but you have keyring 18.0.1 which is incompatible.
> pyicloud-ipd 0.10.1 requires keyrings.alt<2.0,>=1.0, but you have keyrings-alt 4.0.1 which is incompatible.

Yesterday, once, after reinstallation GUI of GnuPG opened and asked me to enter master password. After that I've been asked to confirm 2FA. It looked succesfully but downloader sent me emails about expired cookie. Now I see again error listed previously.  

@boredazfcuk  I'm happy that you reply! To be honest, I tried before use your docker solution but tool can't find ".mounted" file. As I understood, empty file named ".mounted" should be placed inside of docker. Correct?

Many thanks,
M.

**Comment by menkej** [comment]
My guess: There is a secret daemon missing. This highly depends on the desktop environment you're using... This is provided by `gnome-keyring-daemon`p.e. which is part of the gnome desktop environment... Not really an issue with icloudpd.

**Comment by yankkii** [comment]
Thanks @menkej . I did a lot of changes and finally it works. Keyring problem was generated by mess in key management. 
However @boredazfcuk if you could give me advice why your solution can't find .mounted file would be perfect.

**Comment by boredazfcuk** [comment]
> could give me advice why your solution can't find .mounted file would be perfect.

The .mounted file is a fail safe so that the script knows it is downloading to the correct location. For example, when my container downloads the photos, it places them in the `/mnt/iCloud/username/` directory.

If the `/mnt/iCloud` directory dismounts for whatever reason, all photos will be re-downloaded to the root partition. As I sync 3 Apple IDs, the cumulative size of all the photos and videos far exceeds the available space (and total space too, for that matter) of my root partition. Having the script check for the presence of the .mounted file means the script knows the underlying filesystem is mounted correctly.

I tend to create these files on the host machine just by running `touch /mnt/iCloud/<user>/.mounted`

It would also be possible to connect to the running container with `docker exec -it icloudpd /bin/ash` and then create it from there with `touch /home/<user>/iCloud/.mounted`. This could be helpful if you are running the container on a NAS device such as a QNAP or Synology.

**Comment by menkej** [comment]
> The .mounted file is a fail safe so that the script knows it is downloading to the correct location.

Completely out of context but you just gave me a hint how I could solve an Issue I'm having with one of my Proxmox containers that looses the mount to my FritzBox from time to time. Thanks, @boredazfcuk !

**Comment by boredazfcuk** [comment]
It's not the sleekest method of accomplishing things, but it works. 

I wanted it to be invisible to the user so that no configuration was needed, and retrospectively, that would have been the best solution because quite a few people have asked about it.

I did spent quite some time trying to figure out a way of detecting if the directory was mounted from within the container's operating system, but unfortunately, the containerised environment is designed to deliberately hide all that from the containerised OS.

With an LXC container, you could build in a health check script and run from cron every 10 mins. If it doesn't detect the .mounted file on your FritzBox, it attempts to remount the directory. If the remount fails, it waits 2mins before rebooting the container. Also have a startup script which fires out a push notification so you know how often it's rebooting, the 10 minute reboot delay will limit push notifications to 6 per hour.

I didn't put a delay in some of my monitoring scripts once, My server experienced a fault one night and by the morning, I'd found it had send tens of thousands of push notifications as containers were restarting every few seconds... I got blocked by my provider and had to contact their support team with an explanation and grovelling apology lol
