### ISSUE TITLE
No module named 'future'

### ISSUE THREAD

**Issue by freder** [icloud-photos-downloader/icloud_photos_downloader#327]
## Steps to Reproduce
1. run `icloudpd` (with or without any arguments)

## Expected Behavior
should work

## Actual Behavior
produces an error:

```
Traceback (most recent call last):
  File "/Users/freder/miniconda3/bin/icloudpd", line 5, in <module>
    from icloudpd.base import main
  File "/Users/freder/miniconda3/lib/python3.7/site-packages/icloudpd/base.py", line 17, in <module>
    from pyicloud_ipd.exceptions import PyiCloudAPIResponseError
  File "/Users/freder/miniconda3/lib/python3.7/site-packages/pyicloud_ipd/__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "/Users/freder/miniconda3/lib/python3.7/site-packages/pyicloud_ipd/base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "/Users/freder/miniconda3/lib/python3.7/site-packages/pyicloud_ipd/services/__init__.py", line 6, in <module>
    from pyicloud_ipd.services.photos import PhotosService
  File "/Users/freder/miniconda3/lib/python3.7/site-packages/pyicloud_ipd/services/photos.py", line 13, in <module>
    from future.moves.urllib.parse import urlencode
ModuleNotFoundError: No module named 'future'
```

## Context
- running python 3.7 in a conda environment
- installed via `pip install icloudpd`
- `pip install future` says it's already installed
- `icloudpd` 1.7.2
- `pyicloud-ipd` 0.10.1

**Comment by AndreyNikiforov** [comment]
pls try 1.8.0+ -- we updated dependencies. Extra `pip install future` should not be needed. Pls reopen if error persists.
