### ISSUE TITLE
Authentication failed because China mainland account migated to icloud.com.cn instead of icloud.com(with solution)

### ISSUE THREAD

**Issue by QiangGeCode** [icloud-photos-downloader/icloud_photos_downloader#392]
Hi,

Suddenly, this great tool stop working since 18/Nov, I didn't touch anything on the server running it. I didn't change my icloud password as well! 

I installed it in Ubuntu, with Python 3.8.10. Anyone can help me? I really love this tool.

Error message are:

```
2021-11-20 15:02:31 DEBUG    Authenticating...
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
```

**Comment by menkej** [comment]
Hi!
It seems like your authentication token expired. Can you please check again and post the exact command (leaving out your password of course!) you're running?

Thanks
Jörg

**Comment by QiangGeCode** [comment]
Hi,

The token has been expired once 2weeks ago, and I did the 2 steps authentication, then everything went fine before it stop working. Interesting thing is when I try another icloud account, it did working! 

my command is like below, and I run it both in sudo and normal user, show the same error message. 

`/usr/local/bin/icloudpd -d /mnt/nas --username=x@y.com --password=***** --recent 50 --auto-delete`

**Comment by QiangGeCode** [comment]
I just installed a new ubuntu, brand new one, version is 20.04.3. Exactly same error when first time run it. Anybody can help?

**Comment by QiangGeCode** [comment]
When I just tried to run icloud command, then it shows an error: Failed to create the collection

**Comment by QiangGeCode** [comment]
is it because of I'm in China, so the icloud server DNS name is icloud.com.cn? would this possible be the reason of failure?

**Comment by QiangGeCode** [comment]
I might figure out the root cause, but no idea how to solve it. I set the crontab for every 2 hours to download the photo. Then I just read a statement in icloudpd docker page: 

`Be careful if setting a short synchronisation period. Apple have a tendency to throttle connections that are hitting their server too often.`

I guess, I set the interval too short, author recommend for 24h. 

who knows how to solve the problem?

**Comment by Alano-i** [comment]
> I might figure out the root cause, but no idea how to solve it.
> 
> Oringally, I set 2h interval for downloading. 16/Nov, I changed setting the crontab for every 1h to download the photo, which might cause too frequent access to icloud.
> 
> Then I just read a statement in icloudpd docker page:
> 
> `Be careful if setting a short synchronisation period. Apple have a tendency to throttle connections that are hitting their server too often.`
> 
> I guess, I set the interval too short, author recommend for 24h. Apple throttle my connections.
> 
> who knows how to solve the problem?
> 
> Currently, I disabled the crontab schedule downloading tasks, hope it will cooling down and re-enable the authentication.

你好，从19号早上6点多的计划任务开始也出现了相同的问题，我也有两个账号，和你一模一样，但我两个账号都是中国的，都设置6小时更新一次。目前A账号的计划任务完全正常可以正常同步，B账号就报和你一样的错误（AB两个账号当时都是同一天设置好的计划任务），可以判断应该就是账号的问题，或许正如你所说被限制了。我现在将B账号的计划任务停了，希望过几天能解除限制。如果找到解决办法大家可以同步一下，谢谢。

**Comment by QiangGeCode** [comment]
> > I might figure out the root cause, but no idea how to solve it.
> > Oringally, I set 2h interval for downloading. 16/Nov, I changed setting the crontab for every 1h to download the photo, which might cause too frequent access to icloud.
> > Then I just read a statement in icloudpd docker page:
> > `Be careful if setting a short synchronisation period. Apple have a tendency to throttle connections that are hitting their server too often.`
> > I guess, I set the interval too short, author recommend for 24h. Apple throttle my connections.
> > who knows how to solve the problem?
> > Currently, I disabled the crontab schedule downloading tasks, hope it will cooling down and re-enable the authentication.
> 
> 你好，从19号早上6点多的计划任务开始也出现了相同的问题，我也有两个账号，和你一模一样，但我两个账号都是中国的，都设置6小时更新一次。目前A账号的计划任务完全正常可以正常同步，B账号就报和你一样的错误（AB两个账号当时都是同一天设置好的计划任务），可以判断应该就是账号的问题，或许正如你所说被限制了。我现在将B账号的计划任务停了，希望过几天能解除限制。如果找到解决办法大家可以同步一下，谢谢。

好的，希望能尽快解除，以后还是设置一天一次比较安全，就是不知道要过几天才会解除......

**Comment by i-Ethan** [comment]
Same error start at 20/Nov, The crontab interval is 24H.

**Comment by QiangGeCode** [comment]
> 

Which region is your icloud account belong to?

**Comment by QiangGeCode** [comment]
> Same error start at 20/Nov, The crontab interval is 24H.

Which region is your icloud account belong to?

**Comment by ShifengHuGit** [comment]
我也一样啊,.... 我还以为是我个人问题呢...手贱, 登陆了一下icloud的 web客户端后, 然后就再也不好用了.... 的确也出现 要 merge 到 icloud.com 到icloud.com.cn了 ,... 烦死了...咋回事啊...

**Comment by ShifengHuGit** [comment]
我就是点了 那个 到 icloud.com.cn 后 才出的问题. 深度怀疑 就是这个 auth 格式变了...

**Comment by QiangGeCode** [comment]
> 我就是点了 那个 到 icloud.com.cn 后 才出的问题. 深度怀疑 就是这个 auth 格式变了...

我不记得我出问题之前登陆过web的icloud，记不清楚了。。。。。。

这不知道哪位大神可以debug一下，帮忙看看哪里有问题，顺便解决一下

**Comment by i-Ethan** [comment]
> Which region is your icloud account belong to?

中国大陆 😂

**Comment by QiangGeCode** [comment]
所以这个是中国大陆账户特有的问题了... ...

**Comment by QiangGeCode** [comment]
这个软件的作者能帮忙升级一下工具吗？解决一下这个问题

**Comment by QiangGeCode** [comment]
According to above several persons' feedback, this seems to a specific login problem for China mainland users. Probably the reason is icloud.com.cn is used for China mainland, and something is different in authentication process. Could author help to look into this problem?

**Comment by ShifengHuGit** [comment]
Print the resp before parse it where the error happened 

 I have no idea what it should looks before, but currently the body of response seems to be updated due to the migration. 

It is obviously wrong for the code wanted.  not much attributes listed and only a domainToUse, seems that it is says you have to go to other location to get the auth.

**{'domainToUse': 'iCloud.com.cn'}**
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/bin/icloud", line 8, in <module>
    sys.exit(main())
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 221, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'

**Comment by QiangGeCode** [comment]
> Print the resp before parse it where the error happened
> 
> I have no idea what it should looks before, but currently the body of response seems to be updated due to the migration.
> 
> It is obviously wrong for the code wanted. not much attributes listed and only a domainToUse, seems that it is says you have to go to other location to get the auth.
> 
> **{'domainToUse': 'iCloud.com.cn'}** Traceback (most recent call last): File "/var/packages/py3k/target/usr/local/bin/icloud", line 8, in sys.exit(main()) File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main api = pyicloud_ipd.PyiCloudService( File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in **init** self.authenticate() File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 221, in authenticate self.params.update({'dsid': resp['dsInfo']['dsid']}) KeyError: 'dsInfo'

So I think the intial domain should be changed from icloud.com to icloud.com.cn for authentication. have you found where to change it?

**Comment by ShifengHuGit** [comment]
> 

Yes , you are right, and it works fine after  I update the endpoint.

**Comment by ShifengHuGit** [comment]
update the file : site-packages/pyicloud_ipd/base.py

find the keywords icloud.com, there are only 2 lines,  replace it with the icloud.com.cn. 
it should get back


```
150         self._home_endpoint = 'https://www.icloud.com.cn'
151         self._setup_endpoint = 'https://setup.icloud.com.cn/setup/ws/1'
```

**Comment by QiangGeCode** [comment]
> update the file : site-packages/pyicloud_ipd/base.py
> 
> find the keywords icloud.com, there are only 2 lines, replace it with the icloud.com.cn. it should get back
> 
> ```
> 150         self._home_endpoint = 'https://www.icloud.com.cn'
> 151         self._setup_endpoint = 'https://setup.icloud.com.cn/setup/ws/1'
> ```

Haha, great job!!

Actually, I just found those lines almost at the same time! now it's working again!!

**Comment by Alano-i** [comment]
> > update the file : site-packages/pyicloud_ipd/base.py
> > find the keywords icloud.com, there are only 2 lines, replace it with the icloud.com.cn. it should get back
> > ```
> > 150         self._home_endpoint = 'https://www.icloud.com.cn'
> > 151         self._setup_endpoint = 'https://setup.icloud.com.cn/setup/ws/1'
> > ```
> 
> Haha, great job!!
> 
> Actually, I just found those lines almost at the same time! now it's working again!!

That's true. I remembered that it happened after I logged in to icloud.com.cn. It seems that this is the problem. 
Updated base.py and it's worked again.

**Comment by QiangGeCode** [comment]
For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py

**Comment by Alano-i** [comment]
> For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py

更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？
![image](https://user-images.githubusercontent.com/68833595/143485009-7d099955-af36-4d24-ab08-b58a85723eaf.png)

**Comment by Alano-i** [comment]
> update the file : site-packages/pyicloud_ipd/base.py
> 
> find the keywords icloud.com, there are only 2 lines, replace it with the icloud.com.cn. it should get back
> 
> ```
> 150         self._home_endpoint = 'https://www.icloud.com.cn'
> 151         self._setup_endpoint = 'https://setup.icloud.com.cn/setup/ws/1'
> ```

Can icloud.com.cn and icloud.com be verified? If icloud.com cannot be verified, try icloud.com.cn. vice versa. I have two Chinese family accounts. One account is verified by icloud.com.cn, and the other is verified by icloud.com. I don't know why. 
Can you take a look, thank you!

**Comment by boredazfcuk** [comment]
Great find guys. Thanks.

**Comment by QiangGeCode** [comment]
> > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> 
> 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)

你用B账号从web登陆一次icloud.com以后应该就可以了

**Comment by Alano-i** [comment]
> > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > 
> > 
> > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> 
> 你用B账号从web登陆一次icloud.com以后应该就可以了

web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。

**Comment by QiangGeCode** [comment]
> > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > 
> > > 
> > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > 
> > 
> > 你用B账号从web登陆一次icloud.com以后应该就可以了
> 
> web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。

那你的B账号估计不是大陆地区账号，你确认一下。

**Comment by michaelin1208** [comment]
> > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > 
> > > 
> > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > 
> > 
> > 你用B账号从web登陆一次icloud.com以后应该就可以了
> 
> web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。

Same problem, mine and my wife’s Apple ID in same family group, but we are assigned into different host. There is no way to modify host in Apple website. Please let this tool can allow us to set specific host for different backup Apple ID. Thank a lot! Mark for future updates.

**Comment by QiangGeCode** [comment]
> > > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > > 
> > > > 
> > > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > > 
> > > 
> > > 你用B账号从web登陆一次icloud.com以后应该就可以了
> > 
> > 
> > web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。
> 
> Same problem, mine and my wife’s Apple ID in same family group, but we are assigned into different host. There is no way to modify host in Apple website. Please let this tool can allow us to set specific host for different backup Apple ID. Thank a lot! Mark for future updates.

Hi, there is one simple solution for your situation. You could have two linux or docker to run two accounts with or without .cn. before author give a full solution.

**Comment by michaelin1208** [comment]
> > > > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > > > 
> > > > > 
> > > > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > > > 
> > > > 
> > > > 你用B账号从web登陆一次icloud.com以后应该就可以了
> > > 
> > > 
> > > web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。
> > 
> > 
> > Same problem, mine and my wife’s Apple ID in same family group, but we are assigned into different host. There is no way to modify host in Apple website. Please let this tool can allow us to set specific host for different backup Apple ID. Thank a lot! Mark for future updates.
> 
> Hi, there is one simple solution for your situation. You could have two linux or docker to run two accounts with or without .cn. before author give a full solution.

I got it, let me try later. Thanks you!

**Comment by zhang24xiao** [comment]
> > > > > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > > > > 
> > > > > > 
> > > > > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > > > > 
> > > > > 
> > > > > 你用B账号从web登陆一次icloud.com以后应该就可以了
> > > > 
> > > > 
> > > > web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。
> > > 
> > > 
> > > Same problem, mine and my wife’s Apple ID in same family group, but we are assigned into different host. There is no way to modify host in Apple website. Please let this tool can allow us to set specific host for different backup Apple ID. Thank a lot! Mark for future updates.
> > 
> > 
> > Hi, there is one simple solution for your situation. You could have two linux or docker to run two accounts with or without .cn. before author give a full solution.
> 
> I got it, let me try later. Thanks you!

Actually, if you are using cron to sync with icloud schedully, you can use `sed` command to replace `icloud.com` to `icloud.com.cn` before sync the apple ID which uses icloud.com.cn, then use `sed` to replace back to `icloud.com` before sync the apple ID which uses icloud.com....like this:
```
sed -i "s|'https://www.icloud.com'|'https://www.icloud.com.cn'|g" ~/.local/lib/python3.8/site-packages/pyicloud_ipd/base.py && sed -i "s|'https://setup.icloud.com/setup/ws/1'|'https://setup.icloud.com.cn/setup/ws/1'|g" ~/.local/lib/python3.8/site-packages/pyicloud_ipd/base.py && icloudpd -u ID-Uses-icloud.com.cn
sed -i "s|'https://www.icloud.com.cn'|'https://www.icloud.com'|g" ~/.local/lib/python3.8/site-packages/pyicloud_ipd/base.py && sed -i "s|'https://setup.icloud.com.cn/setup/ws/1'|'https://setup.icloud.com/setup/ws/1'|g" ~/.local/lib/python3.8/site-packages/pyicloud_ipd/base.py && icloudpd -u ID-Uses-icloud.com

**Comment by neohob** [comment]
我用docker版本，改不了，还得自己封一个太麻烦了，什么时候能修复呢

**Comment by shaoj0013** [comment]
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/cmdline.py", line 200, in main
    api = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 219, in authenticate
    self.params.update({'dsid': resp['dsInfo']['dsid']})
KeyError: 'dsInfo'
2021-12-16 09:30:50 INFO     Correct owner on config directory, if required
2021-12-16 09:30:50 INFO     Correct group on config directory, if required
2021-12-16 09:30:50 INFO     Generate 2FA cookie using password stored in keyring file.
iCloud Password: 
 

我这是一样的么？？我也是docker部署的！群晖还是dsm7的！没办法修改base.py文件

**Comment by apheyliu** [comment]
> > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > 
> > > 
> > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > 
> > 
> > 你用B账号从web登陆一次icloud.com以后应该就可以了
> 
> web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。

我跟你一样的问题，两个账号怎么也弄不成一致的。没办法自己修改了一下base.py，判断当前apple_id是哪一个，替换设置不同的host。

**Comment by shaoj0013** [comment]
> > > > > For your info, the file need to be updated, the absolute path is: /usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py
> > > > 
> > > > 
> > > > 更新base.py为icloud.com.cn后，A账号可以同步了，但是B账号又不行了，同样都是中国的AB两个账号，一个是通过icloud.com完成验证，另一个却是通过icloud.com.cn验证，请问知道如何改成一样的吗？ ![image](https://user-images.githubusercontent.com/68833595/143485573-ea26b75f-508a-4b77-a34a-c037fa367c69.png)
> > > 
> > > 
> > > 你用B账号从web登陆一次icloud.com以后应该就可以了
> > 
> > 
> > web登陆一次icloud.com也似乎不起作用，不会自动引导到icloud.com.cn去，而我手动通过icloud.com.cn登录账户，却会引导我去iCloud.com登录，就像发的图片那样，不然就无法进入。
> 
> 我跟你一样的问题，两个账号怎么也弄不成一致的。没办法自己修改了一下base.py，判断当前apple_id是哪一个，替换设置不同的host。
我的解决了！！配置文件加一行就好！

  --env icloud_china=True \

**Comment by 404gods** [comment]
我的问题更奇怪，我是中国大陆的Apple ID，登陆网页版icloud.com.cn时非让我去登陆icloud.com，docker版本的icloudpd如果加入了变量env icloud_china=True \，运行时日志提示WARNING  Downloading from icloud.com.cn is untested，2次输入密码后不会有2FA的步骤就停止了。
而不加变量env icloud_china=True \，使用icloud.com却一切正常。
我在本地不同的网络坏境下测试ping icloud.com.cn和icloud.com，都是美国apple地址17.253.144.10
真是搞不懂

**Comment by shaoj0013** [comment]
配置信息发出来看看！

**Comment by shaoj0013** [comment]
我就是中国账户，加了变量后使用正常！

**Comment by lewangdev** [comment]
中国的 icloud 用户可以用这个

```
docker pull lewangdev/icloudpd:latest
```

我在 tag 为 1.7.2 原镜像基础上做了修改：

把 `base.py`

```python
        self._home_endpoint = 'https://www.icloud.com'
        self._setup_endpoint = 'https://setup.icloud.com/setup/ws/1'
```

改为：

```python
        self._home_endpoint = 'https://www.icloud.com.cn' if os.environ.get('icloud_china', '1') == '1' else 'https://www.icloud.com'
        self._setup_endpoint = 'https://setup.icloud.com.cn/setup/ws/1' if os.environ.get('icloud_china', '1') == '1' else 'https://setup.icloud.com/setup/ws/1'
```

然后使用以下 dockerfile 构建出新的镜像：

```Dockerfile
FROM icloudpd/icloudpd

COPY base.py /usr/lib/python3.8/site-packages/pyicloud_ipd/base.py
```

新镜像默认使用中国的域名，也可以通过传入环境变量禁止使用中国域名，如下：

```
--env icloud_china=0 \
```

**Comment by jaymier** [comment]
> 中国大陆 icloud 用户可以用这个
你好，你这个镜像怎么同步？我看容器里面没有sync-icloud.sh这个脚步，那么启动脚步是哪个呢？

**Comment by lewangdev** [comment]
> 
类似这样
```sh
icloud_home=/mnt/disk0/le/Pictures/icloud
mkdir -p ${icloud_home}
docker run -it --rm --name icloud-le \
    -v ${icloud_home}/Photos:/data \
    -v ${icloud_home}/cookies:/cookies \
    -e TZ=Asia/Shanghai \
    lewangdev/icloudpd:latest \
    icloudpd --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m-%d} \
    --username <your_icloud_email> \
    --password <your_icloud_password> \
    --size original \
    --auto-delete
```

**Comment by AndreyNikiforov** [comment]
icloudpd >=1.9.0 support `--domain cn` parameter to work from China.

**Comment by shaoj0013** [comment]
docker部署命令，在群晖下无法安装

Andrey Nikiforov ***@***.***>于2023年2月12日 周日02:19写道：

**Comment by shaoj0013** [comment]
又不能用了

2023-03-10 14:19:38 INFO     Next synchronisation at 02:19:29
2023-03-10 14:27:02 INFO     ***** boredazfcuk/icloudpd container for
icloud_photo_downloader started *****
2023-03-10 14:27:02 INFO     ***** For support, please go here:
https://github.com/boredazfcuk/docker-icloudpd *****
2023-03-10 14:27:02 INFO     ***** /usr/local/bin/sync-icloud.sh date:
2023/01/19_22:02 *****
2023-03-10 14:27:02 INFO     ***** /usr/local/bin/sync-icloud.sh hash:
643f09e7f3436290dea6d857776832a2 *****
2023-03-10 14:27:02 INFO     Alpine Linux 3.17.1
2023-03-10 14:27:02 INFO     Python version: 3.10.9
2023-03-10 14:27:04 INFO     icloudpd version: 1.7.2
2023-03-10 14:27:05 INFO     pyicloud version: 1.0.0
2023-03-10 14:27:05 INFO     Running user id: 0
2023-03-10 14:27:05 INFO     Running group id: 0
2023-03-10 14:27:05 INFO     Local user: admin:1024
2023-03-10 14:27:05 INFO     Local group: users:100
2023-03-10 14:27:05 INFO     Force GID: False
2023-03-10 14:27:05 INFO     LAN IP Address: 192.168.115.1
2023-03-10 14:27:05 INFO     Default gateway: 192.168.115.254
2023-03-10 14:27:05 INFO     DNS server: 127.0.0.11
2023-03-10 14:27:05 INFO     IP address for icloud.com.cn: 103.115.248.1
2023-03-10 14:27:29 INFO     Route check to icloud.com.cn successful
2023-03-10 14:27:29 INFO     Apple ID: ***@***.***
2023-03-10 14:27:29 INFO     Authentication Type: 2FA
2023-03-10 14:27:29 INFO     Cookie path: /config/shaoj0013qqcom
2023-03-10 14:27:29 INFO     Cookie expiry notification period: 7
2023-03-10 14:27:29 INFO     Download destination directory:
/mnt/admin/Photos/iCloud/shaoj0013
2023-03-10 14:27:29 INFO     Folder structure: {:%Y/%m}
2023-03-10 14:27:29 INFO     Directory permissions: 750
2023-03-10 14:27:29 INFO     File permissions: 640
2023-03-10 14:27:29 INFO     Synchronisation interval: 43200
2023-03-10 14:27:29 INFO     Synchronisation delay (minutes): 0
2023-03-10 14:27:29 INFO     Set EXIF date/time: False
2023-03-10 14:27:29 INFO     Auto delete: True
2023-03-10 14:27:29 INFO     Photo size: original
2023-03-10 14:27:29 INFO     Single pass mode: False
2023-03-10 14:27:29 INFO     Skip download check: False
2023-03-10 14:27:29 INFO     Skip live photos: False
2023-03-10 14:27:29 INFO     Number of most recently added photos to
download: 100
2023-03-10 14:27:29 INFO     Downloading photos from album: Download All
Photos
2023-03-10 14:27:29 INFO     Stop downloading when prexisiting files count
is: Download All Photos
2023-03-10 14:27:29 INFO     Live photo size: original
2023-03-10 14:27:29 INFO     Skip videos: False
2023-03-10 14:27:29 INFO     Convert HEIC to JPEG: false
2023-03-10 14:27:29 INFO     JPEG conversion quality: 90
2023-03-10 14:27:29 INFO     Downloading from: icloud.com.cn
2023-03-10 14:27:29 WARNING  Downloading from icloud.com.cn is untested.
Please report issues at
https://github.com/boredazfcuk/docker-icloudpd/issues
2023-03-10 14:27:29 INFO     Nextcloud synchronisation trigger: Disabled
2023-03-10 14:27:29 INFO     Group, users:100, already created
2023-03-10 14:27:29 INFO     User, admin:1024, already created
2023-03-10 14:27:29 INFO     Correct owner on icloudpd temp directory, if
required
2023-03-10 14:27:29 INFO     Correct group on icloudpd temp directory, if
required
2023-03-10 14:27:29 INFO     Correct owner on config directory, if required
2023-03-10 14:27:29 INFO     Correct group on config directory, if required
2023-03-10 14:27:29 INFO     Correct owner on keyring directory, if required
2023-03-10 14:27:29 INFO     Correct group on keyring directory, if required
2023-03-10 14:27:29 INFO     Configure password
2023-03-10 14:27:29 INFO     Using password stored in keyring file:
/config/python_keyring/keyring_pass.cfg
2023-03-10 14:27:29 INFO     Check download directory mounted correctly
2023-03-10 14:27:29 INFO     Failsafe file
/mnt/admin/Photos/iCloud/shaoj0013/.mounted exists, continuing
2023-03-10 14:27:29 INFO     Correct owner on icloudpd temp directory, if
required
2023-03-10 14:27:29 INFO     Correct group on icloudpd temp directory, if
required
2023-03-10 14:27:29 INFO     Correct owner on config directory, if required
2023-03-10 14:27:29 INFO     Correct group on config directory, if required
2023-03-10 14:27:29 INFO     Correct owner on keyring directory, if required
2023-03-10 14:27:29 INFO     Correct group on keyring directory, if required
2023-03-10 14:27:29 INFO     Sync user admin
2023-03-10 14:27:29 INFO     Synchronisation starting at 14:27:29
2023-03-10 14:27:29 INFO     Check 2FA Cookie
2023-03-10 14:27:29 INFO     Cookie exists, check expiry date
2023-03-10 14:27:29 INFO     Valid two factor authentication cookie found.
Days until expiration: 87
2023-03-10 14:27:29 INFO     Check download directory mounted correctly
2023-03-10 14:27:29 INFO     Failsafe file
/mnt/admin/Photos/iCloud/shaoj0013/.mounted exists, continuing
2023-03-10 14:27:29 INFO     Check for new files using password stored in
keyring file
2023-03-10 14:27:29 INFO     Generating list of files in iCloud. This may
take a long time if you have a large photo collection. Please be patient.
Nothing is being downloaded at this time
2023-03-10 14:27:41 ERROR    Failed check for new files files
2023-03-10 14:27:41 ERROR     - Can you log into iCloud.com without
receiving pop-up notifications?
2023-03-10 14:27:41 ERROR    Error debugging info:
2023-03-10 14:27:41 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 829, in
__call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1066, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 610, in
invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 565, in
main
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 379, in
download_photo
    if photo.item_type not in ("image", "movie"):
AttributeError: 'PhotoAsset' object has no attribute 'item_type'
2023-03-10 14:27:41 ERROR    ***** Please report problems here:
https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-03-10 14:27:41 INFO     Web cookie expires: 2023-05-07 @ 04:01:24
2023-03-10 14:27:41 INFO     Two factor authentication cookie expires:
2023-06-06 @ 04:01:16
2023-03-10 14:27:41 INFO     Days remaining until expiration: 87
2023-03-10 14:27:41 INFO     iCloud login counter = 1
2023-03-10 14:27:41 INFO     Synchronisation ended at 14:27:41
2023-03-10 14:27:41 INFO     Total time taken: 00:00:12
2023-03-10 14:27:41 INFO     Next synchronisation at 02:27:29

邵俊 ***@***.***>于2023年2月12日 周日14:16写道：
