### ISSUE TITLE
icloudpd takes 5 minutes to start

### ISSUE THREAD

**Issue by JasonSanDiego** [icloud-photos-downloader/icloud_photos_downloader#397]
When running icloudpd on a high-end Windows 10 computer with WSL 2 (Ubuntu 20.04, Python 3.8.10), it takes _forever_ (nearly five minutes actually) to actually execute. Note that my timing below isn't 100% accurate because it is prompting for a username, but I pressed Ctrl C almost as soon a seeing it come up.

```
DESKTOP-I2IUFS5:~$ time icloudpd
iCloud username/email: ^CAborted!

real    4m40.099s
user    0m0.183s
sys     0m0.001s
```

When I install and run this on a native Linux install, it starts instantly.

I installed it with pip.

Running python3 brings up the REPL immediately.

How do I go about debugging what is holding things up?

**Comment by JasonSanDiego** [comment]
I started running the imports manually in the python REPL. It seems like this line is the one taking a LONG time.
`from pyicloud_ipd.exceptions import PyiCloudAPIResponseError`

When I interrupt, here's what I get in the traceback.

Any ideas on what is going on in this import process to slow things down?

```
CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/services/__init__.py", line 7, in <module>
    from pyicloud_ipd.services.account import AccountService
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/services/account.py", line 5, in <module>
    from pyicloud_ipd.utils import underscore_to_camelcase
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/utils.py", line 2, in <module>
    import keyring
  File "/usr/local/lib/python3.8/dist-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python3.8/dist-packages/keyring/core.py", line 185, in <module>
    init_backend()
  File "/usr/local/lib/python3.8/dist-packages/keyring/core.py", line 66, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/local/lib/python3.8/dist-packages/keyring/util/__init__.py", line 20, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keyring/backend.py", line 178, in get_all_keyring
    return list(util.suppress_exceptions(viable_classes,
  File "/usr/local/lib/python3.8/dist-packages/keyring/util/__init__.py", line 29, in suppress_exceptions
    for callable in callables:
  File "/usr/local/lib/python3.8/dist-packages/keyring/backend.py", line 171, in is_class_viable
    keyring_cls.priority
  File "/usr/local/lib/python3.8/dist-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/local/lib/python3.8/dist-packages/keyring/backends/kwallet.py", line 26, in priority
    bus = dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/exceptions.py", line 47, in __init__
    def __init__(self, *args, **kwargs):
KeyboardInterrupt
```

**Comment by vinzBad** [comment]
Looks like it waiting for a dbus connection for the import password from keyring feature, so that's something you need to fix on your system. https://www.freedesktop.org/wiki/Software/dbus/

**Comment by JasonSanDiego** [comment]
Thanks so much! This got me on the right path, and eventually I found the right "workaround" here: https://github.com/pypa/pip/issues/7883

`unset DISPLAY`

I had DISPLAY set even though I don't have a window manager running. I don't remember if I was doing something at some point or if it came installed that way by default. At any rate, now icloudpd runs instantly.

**Comment by sinnerlolqt** [comment]
How do I unsubscribe from this list please?

**Comment by menkej** [comment]
Just click on the unsubscribe link in the notification mail or on the GitHub page for this issue.

— 
Von meinem C64 gesendet

> Am 14.12.2021 um 19:44 schrieb John Smith ***@***.***>:
> 
> ﻿
> How do I unsubscribe from this list please?
> Sent from my iPhone
>

**Comment by archsinner** [comment]
Still getting emails even though Im unsubbed

**Comment by archsinner** [comment]
Got it jeez
