### ISSUE TITLE
Error on macOS: ...cannot import name 'Callable' from 'collections'

### ISSUE THREAD

**Issue by crash-bash** [icloud-photos-downloader/icloud_photos_downloader#464]
## Overview

UPDATE-1: Command **pip3 install --upgrade keyring** fixed the behavior. Now icloudpd starts successfully. But the installation documentation may need to be updated.

UPDATE-2: In the end, I uninstalled the latest version of Python and installed the required version of Python 3.8. After that, everything worked fine. The last post has the commands I used to do this.

Hi! I would be grateful for help with installing icloudp on my macOS. Following the documentation, everything installs successfully, but at startup I get an error: "ImportError: cannot import name 'Callable' from 'collections'".

## Steps to Reproduce

1. The installation of Python with Homebrew was successful. I used the **brew install python** command.
```
Mac-mini-Roman:~ roman$ python --version
-bash: python: command not found
Mac-mini-Roman:~ roman$ python3 --version
Python 3.10.6

```
2. Command **pip install icloudpd** from the documentation did not work, but command **pip3 install icloudpd** successfully installed the icloudpd-1.7.2.

```
Mac-mini-Roman:~ roman$ pip install icloudpd
-bash: pip: command not found
Mac-mini-Roman:~ roman$ pip3 install icloudpd
Collecting icloudpd
  Using cached icloudpd-1.7.2-py2.py3-none-any.whl (34 kB)
Collecting schema==0.7.2
  Using cached schema-0.7.2-py2.py3-none-any.whl (16 kB)
....
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Using cached tzdata-2022.2-py2.py3-none-any.whl (336 kB)
Installing collected packages: pytz, keyrings.alt, keyring, click, urllib3, tzdata, tqdm, six, piexif, idna, future, contextlib2, charset-normalizer, certifi, schema, requests, pytz-deprecation-shim, python-dateutil, tzlocal, pyicloud-ipd, icloudpd
Successfully installed certifi-2022.6.15 charset-normalizer-2.1.1 click-6.7 contextlib2-21.6.0 future-0.18.2 icloudpd-1.7.2 idna-3.3 keyring-8.7 keyrings.alt-1.3 piexif-1.1.3 pyicloud-ipd-0.10.1 python-dateutil-2.8.1 pytz-2022.2.1 pytz-deprecation-shim-0.1.0.post0 requests-2.28.1 schema-0.7.2 six-1.16.0 tqdm-4.56.0 tzdata-2022.2 tzlocal-4.2 urllib3-1.26.12
```

3. Attempting to start **icloudp** fails:

```
Mac-mini-Roman:~ roman$ icloudpd
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 5, in <module>
    from icloudpd.base import main
  File "/usr/local/lib/python3.10/site-packages/icloudpd/base.py", line 17, in <module>
    from pyicloud_ipd.exceptions import PyiCloudAPIResponseError
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/services/__init__.py", line 7, in <module>
    from pyicloud_ipd.services.account import AccountService
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/services/account.py", line 5, in <module>
    from pyicloud_ipd.utils import underscore_to_camelcase
  File "/usr/local/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 2, in <module>
    import keyring
  File "/usr/local/lib/python3.10/site-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python3.10/site-packages/keyring/core.py", line 14, in <module>
    from . import backend
  File "/usr/local/lib/python3.10/site-packages/keyring/backend.py", line 18, in <module>
    from .util import properties
  File "/usr/local/lib/python3.10/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

Have a great day!

**Comment by boredazfcuk** [comment]
The app is not compatible with Python 3.10. You either need to downgrade to Python 3.8 or run this command to fix the problem:
```
   sed -i 's/from collections import Callable/from collections.abc import Callable/' "/usr/local/lib/python3.10/site-packages/keyring/util/properties.py"
```

After that you'll probably run into errors about it not being able to find encodestring and decodestring. Fix those issues with this command:
```
   sed -i -e 's/password_encrypted = base64.decodestring(password_base64)/password_encrypted = base64.decodebytes(password_base64)/' \
      -e 's/password_base64 = base64.encodestring(password_encrypted).decode()/password_base64 = base64.encodebytes(password_encrypted).decode()/' \
      "/usr/local/lib/python3.10/site-packages/keyrings/alt/file_base.py"
```

**Comment by crash-bash** [comment]
Thank you, it all worked out!

1. Remove icloudpd & Python 3.10: **pip3 uninstall icloudpd** and **brew uninstall python**
2. Install Python 3.8: **brew install python@3.8**
3. Install icloudpd: **pip3.8 install icloudpd**
4. Success! :))

```
Mac-mini-Roman:~ roman$ python3.8 --version
Python 3.8.13
Mac-mini-Roman:~ roman$ pip3.8 --version
pip 22.2.2 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
Mac-mini-Roman:~ roman$ icloudpd --version
icloudpd, version 1.7.2
```
