### ISSUE TITLE
failed to download photo ('PhotoAsset' object)

### ISSUE THREAD

**Issue by qls-dong** [icloud-photos-downloader/icloud_photos_downloader#607]
## Overview
failed to download photo

## Context
master branch

DEBUG Authenticating...
DEBUG Looking up all photos and videos from album All Photos...
DEBUG Downloading ***** original photos and videos to /iCloud ...
ERROR    Failed to download new files
ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
ERROR    Error debugging info:
ERROR    Traceback (most recent call last):

## Actual Behavior
   File "/usr/bin/icloudpd", line 8, in <module>
     sys.exit(main())
   File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
     return self.main(*args, **kwargs)
   File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
     rv = self.invoke(ctx)
   File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
     return __callback(*args, **kwargs)
   File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
     core(
   File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 728, in core
     download_photo(consecutive_files_found, item)
   File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 354, in download_photo_
     if photo.item_type not in ("image", "movie"):
 AttributeError: 'PhotoAsset' object has no attribute 'item_type'

**Comment by qls-dong** [comment]
use pprint this photo, photo only have id.  
##Code
pprint.pprint(photo)

##Result
photo=<PhotoAsset: id=XXXXXXX>

 is why?

**Comment by qls-dong** [comment]
oh i know
