### ISSUE TITLE
Script Fails on Delete

### ISSUE THREAD

**Issue by sailingbikeruk** [icloud-photos-downloader/icloud_photos_downloader#615]
## Overview
I have been downloading a large volume (40000+) photos,running with --delete-after-download. On a small number of occasions the script failed with this error:
```

2023-04-02 10:16:35 INFO     Deleting CimlXrfW0AADRLn.jpg
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/base.py", line 288, in main
    core(
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/base.py", line 730, in core
    delete_photo(item)
  File "/usr/local/lib/python3.8/dist-packages/icloudpd/base.py", line 709, in delete_photo
    icloud.photos.session.post(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/usr/local/lib/python3.8/dist-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: INTERNAL_ERROR (INTERNAL_ERROR)
```
As someone who does not write python it is an unhelpful error.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
I couldn't reproduce it on-demand
 
## Expected Behavior
Improved error handling, with use friendly errors (if possible)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

**Comment by AndreyNikiforov** [comment]
fixed in [v1.14.2](https://github.com/icloud-photos-downloader/icloud_photos_downloader/releases/tag/v1.14.2)
