### ISSUE TITLE
[China] [653] Failed to execute script 'exec' due to unhandled exception!

### ISSUE THREAD

**Issue by xun188** [icloud-photos-downloader/icloud_photos_downloader#621]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Use command
./icloudpd icloudpd --directory /Users/ji/Downloads/Photo --domain cn

023-04-12 17:37:34 INFO     Two-step/two-factor authentication is required!
Traceback (most recent call last):
  File "exec.py", line 63, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "icloudpd/base.py", line 288, in main
  File "icloudpd/base.py", line 571, in core
  File "icloudpd/authentication.py", line 48, in authenticate_
  File "icloudpd/authentication.py", line 55, in request_2sa
  File "pyicloud_ipd/base.py", line 266, in trusted_devices
  File "requests/sessions.py", line 600, in get
  File "pyicloud_ipd/base.py", line 105, in request
  File "pyicloud_ipd/base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com
[653] Failed to execute script 'exec' due to unhandled exception!

**Comment by AndreyNikiforov** [comment]
@xun188 unfortunately `-domain cn` parameter does not work as expected. I am unable to test and debug that parameter because I am outside of mainland China. VPN did not help either.

**Comment by boredazfcuk** [comment]
Hi,
My container now works for users in China. The --domain parameter will allow users to download files provided a valid 2FA cookie exists. The error only occurs when attempting to generate the cookie.

To allow users in China to successfully generate a cookie, I install a patched version of icloud_photos_downloader 1.7.2 into a virtual environment, then launch that for the cookie generation process.

**Comment by xun188** [comment]
> @xun188 unfortunately `-domain cn` parameter does not work as expected. I am unable to test and debug that parameter because I am outside of mainland China. VPN did not help either.

thank you for your hard work and reply,Hope will be solved one day
