### ISSUE TITLE
ERROR Failed check for new files files - ValueError: invalid literal for int() with base 16: b'' - v1.12.0

### ISSUE THREAD

**Issue by freezah** [icloud-photos-downloader/icloud_photos_downloader#623]
## Overview
Suddenly stopped syncing files. Redeployed container with latest image version and still hitting same issue.

## Expected Behavior
Download all new files from iCloud

## Actual Behavior
Crashing at new files few days old

## Context
Getting following log:

/xxx/2023-04/IMG_3806.PNG
/xxx/2023-04/IMG_3805.HEIC
/xxx/2023-04/IMG_3804.HEIC
/xxx/2023-04/IMG_3803.PNG
2023-04-15 11:07:50 ERROR    Failed check for new files files
2023-04-15 11:07:50 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-04-15 11:07:50 ERROR    Error debugging info:
2023-04-15 11:07:50 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_v1.12.0/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/icloudpd/base.py", line 727, in core
    item = next(photos_iterator)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 295, in photos
    request = self.photos_request(offset)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 276, in photos_request
    return self.service.session.post(
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 71, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/opt/icloudpd_v1.12.0/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
2023-04-16T11:26:58.493569254Z 2023-04-16 13:26:58 INFO     Web cookie expires: 2023-06-15 @ 08:56:49
2023-04-16T11:26:58.494308260Z 2023-04-16 13:26:58 INFO     Two factor authentication cookie expires: 2023-07-15 @ 08:57:01
2023-04-16T11:26:58.495098432Z 2023-04-16 13:26:58 INFO     Days remaining until expiration: 89
2023-04-16T11:26:58.497301664Z 2023-04-16 13:26:58 INFO     Synchronisation ended at 13:26:58
2023-04-16T11:26:58.498772563Z 2023-04-16 13:26:58 INFO     Total time taken: 00:04:58
2023-04-16T11:26:58.500235627Z 2023-04-16 13:26:58 INFO     Next synchronisation at 13:22:00

**Comment by AndreyNikiforov** [comment]
@freezah logs don't seem to be produced by the app from this project. Please double check what command you are running.

The error looks like dup of #622 - let's consolidate discussion there.

**Comment by AndreyNikiforov** [comment]
> @freezah logs don't seem to be produced by the app from this project. Please double check what command you are running.
> 
> The error looks like dup of #622 - let's consolidate discussion there.

My bad - error may be different.

**Comment by freezah** [comment]
@AndreyNikiforov can you re-open then this bug ?

**Comment by AndreyNikiforov** [comment]
> @AndreyNikiforov can you then re-open this issue ?

What container/binary are you running? There are other projects that use `icloudpd` and based on the logs you may be using one of them and not binarie/container `icloudpd` project itself. If that is indeed the case, you may be better of opening the issue for the project you are using binaries/container from.
