### ISSUE TITLE
Error occurred (possibly) after logging into Remote Desktop

### ISSUE THREAD

**Issue by g0lg0-93** [icloud-photos-downloader/icloud_photos_downloader#647]
```
Traceback (most recent call last):
  File "icloudpd.py", line 5, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "icloudpd\base.py", line 283, in main
  File "icloudpd\base.py", line 730, in core
  File "icloudpd\base.py", line 708, in delete_photo
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\base.py", line 105, in request
  File "pyicloud_ipd\base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Invalid global session
[10292] Failed to execute script 'icloudpd' due to unhandled exception!
```

First and foremost, I wanted to say thank you for this excellent tool. It has saved me SO much time, even though this run has barely scratched the surface.

I've run into this error running this tool on a Windows 10 (64-bit) (local) remote desktop, the local directory is an external USB hard drive. I'm not sure when the error occurred, but when I logged into this remote desktop this morning I had seen it. Looking at the error, it was unable to handle deleting an item.

Two questions:
1. The remote desktop doesn't go to sleep or anything, but do you think when the remote user logs in, it throws this error?
2. Is there an option to silent the error and continue?

Look forward to your response!

**Comment by AndreyNikiforov** [comment]
Did it happen only once and work all other times when you re-connected to remote desktop? Does `icloudpd` work reliably without remote desktop (==on the console)?

**Comment by g0lg0-93** [comment]
I posted this and then restarted the download process. I've logged into the remote desktop multiple times throughout the day to check and the downloading process hasnt been interrupted.

**Comment by g0lg0-93** [comment]
Logged into the Remote Desktop this morning and it had the failure. It looks like it failed at 20:08PM 29/06/2023, so it's not related to remote logging in. 

Is there a location for logs?

**Comment by g0lg0-93** [comment]
`Traceback (most recent call last):
  File "icloudpd.py", line 5, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "icloudpd\base.py", line 283, in main
  File "icloudpd\base.py", line 730, in core
  File "icloudpd\base.py", line 708, in delete_photo
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\base.py", line 105, in request
  File "pyicloud_ipd\base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: INTERNAL_ERROR (INTERNAL_ERROR)
[11696] Failed to execute script 'icloudpd' due to unhandled exception!`

Past couple days this is the error that's been popping up. It's now become an internal error, any suggestions?

**Comment by AndreyNikiforov** [comment]
@g0lg0-93 pls see if v1.14.1+ fixes your issue
