### ISSUE TITLE
new 1.14.0，no china access

### ISSUE THREAD

**Issue by jiaoting** [icloud-photos-downloader/icloud_photos_downloader#650]
C:\Users\jiaoting\Downloads\下载暂存\icloudpd>icloud.exe --username jiaoting@126.com --delete-from-keyring --domain cn --outputfile
Enter iCloud password for jiaoting@126.com:
Save password in keyring?  [y/N]: n
Two-step authentication required. Your trusted devices are:
Traceback (most recent call last):
  File "icloud.py", line 5, in <module>
  File "pyicloud_ipd\cmdline.py", line 226, in main
  File "pyicloud_ipd\base.py", line 266, in trusted_devices
  File "requests\sessions.py", line 602, in get
  File "pyicloud_ipd\base.py", line 105, in request
  File "pyicloud_ipd\base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
[11904] Failed to execute script 'icloud' due to unhandled exception!

**Comment by lingluan5210** [comment]
I also encountered this problem, I am also a Chinese appleid, do you have a solution?
