### ISSUE TITLE
[China] no china access

### ISSUE THREAD

**Issue by lingluan5210** [icloud-photos-downloader/icloud_photos_downloader#667]
2023-07-17 17:32:55 DEBUG    Authenticating...
2023-07-17 17:33:01 INFO     Two-step/two-factor authentication is required
2023-07-17 17:33:01 ERROR    statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
Traceback (most recent call last):
  File "starters\icloudpd.py", line 5, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 299, in main
  File "icloudpd\base.py", line 721, in core
  File "icloudpd\authentication.py", line 47, in authenticate_
  File "icloudpd\authentication.py", line 54, in request_2sa
  File "pyicloud_ipd\base.py", line 266, in trusted_devices
  File "requests\sessions.py", line 602, in get
  File "pyicloud_ipd\base.py", line 105, in request
  File "pyicloud_ipd\base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
[16720] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by lingluan5210** [comment]
Two-step authentication required. Your trusted devices are:
Traceback (most recent call last):
  File "starters\icloud.py", line 5, in <module>
  File "pyicloud_ipd\cmdline.py", line 226, in main
  File "pyicloud_ipd\base.py", line 266, in trusted_devices
  File "requests\sessions.py", line 602, in get
  File "pyicloud_ipd\base.py", line 105, in request
  File "pyicloud_ipd\base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request https://accountservice.p00.prod.me.com:443/api/get_challenge_devices, accountservice.p00.prod.me.com.
[4348] Failed to execute script 'icloud' due to unhandled exception!

**Comment by hzbb0930** [comment]
I also encountered this problem.

**Comment by boredazfcuk** [comment]
The boredazfcuk/icloudpd DockerHub container works in China.

**Comment by hzbb0930** [comment]
> The boredazfcuk/icloudpd DockerHub container works in China.

I use ubuntu. How can I use it?

**Comment by boredazfcuk** [comment]
Install Docker on Ubuntu, then create a container:

https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md

Make sure you set both the **icloudpd_china** and **auth_china** variables to **true**

**Comment by hzbb0930** [comment]
> Install Docker on Ubuntu, then create a container:
> 
> 
> 
> https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md
> 
> 
> 
> Make sure you set both the **icloudpd_china** and **auth_china** variables to **true**

OK, I‘ll try it. Thank you for your help.

**Comment by hzbb0930** [comment]
> > Install Docker on Ubuntu, then create a container:
> > 
> > 
> > 
> > https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md
> > 
> > 
> > 
> > Make sure you set both the **icloudpd_china** and **auth_china** variables to **true**
> 
> OK, I‘ll try it. Thank you for your help.

2023-07-25 20:14:06 ERROR    Failed check for new files files
2023-07-25 20:14:06 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-07-25 20:14:06 ERROR    Error debugging info:
2023-07-25 20:14:06 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
    icloud = authenticator(domain)(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 32, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
    raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-07-25 20:14:06 ERROR    ***** Please report problems 
What should I do now?

**Comment by hzbb0930** [comment]
> Install Docker on Ubuntu, then create a container:
> 
> 
> 
> https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md
> 
> 
> 
> Make sure you set both the **icloudpd_china** and **auth_china** variables to **true**

2023-07-25 20:14:06 ERROR Failed check for new files files
2023-07-25 20:14:06 ERROR - Can you log into icloud.com.cn without receiving pop-up notifications?
2023-07-25 20:14:06 ERROR Error debugging info:
2023-07-25 20:14:06 ERROR Traceback (most recent call last):
File "/opt/icloudpd_latest/bin/icloudpd", line 8, in 
sys.exit(main())
^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return _callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 285, in main
core(
File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 665, in core
icloud = authenticator(domain)(
^^^^^^^^^^^^^^^^^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 32, in authenticate
icloud = pyicloud_ipd.PyiCloudService(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in init
self.authenticate()
File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 234, in authenticate
raise PyiCloudConnectionException(msg)
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
2023-07-25 20:14:06 ERROR ***** Please report problems
What should I do now?

**Comment by boredazfcuk** [comment]
>pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter

This error means **auth_china** is not set to **true** as it is attempting to authenticate to icloud.com (instead of icloud.com.cn), but being rejected.

**Comment by hzbb0930** [comment]
> >pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter
> 
> 
> 
> This error means **auth_china** is not set to **true** as it is attempting to authenticate to icloud.com.
> 
> 
> 
> Edit: When you have both **icloud_china** and **auth_china** set to **true** you should see something like this:
> 
> ```
> 
> 2023-07-25 22:16:00 INFO     Downloading from: icloud.com.cn
> 
> 2023-07-25 22:16:00 INFO     Authentication domain: cn
> 
> ```
> 
> in your container's log file

I have a question. Will this script steal my privacy?

**Comment by boredazfcuk** [comment]
I know the script won't do that, because I wrote it.

I can't confirm the same for icloud_photos_downloader, or any of the dependencies it requires, or even operating system it needs to be installed on.

**Comment by hzbb0930** [comment]
> I know the script won't do that, because I wrote it. It's also fairly easy to follow as the log file it produces double as comments for the script, so you can read through and see it's not really doing anything along those lines...
> 
> I can't confirm the same for icloud_photos_downloader, or any of the dependencies it requires, or even operating system it needs to be installed on.

OK, thank you very much for your contribution. I attach great importance to my privacy. Thank you for your answer.

**Comment by Sillyxn** [comment]
Chinese users need to add the parameter domain cn to restore normal use of the program, provided that they manually log in to apple.com.cn and then add the domain cn parameter to use it!
