### ISSUE TITLE
Download keeps stopping after some minutes

### ISSUE THREAD

**Issue by mariomaz87** [icloud-photos-downloader/icloud_photos_downloader#680]
## Overview
Hi, I'm trying to download all my iCloud Photo data but the download stops every once in a while.

## Steps to Reproduce
1. python3 -m icloudpd --directory /media/mario/iCloudpd/ --username mymail --password mypassword --recent 5000 --folder-structure {:%Y/%m}.

## Expected Behavior
I expect the download to complete in one session

## Actual Behavior
The download stops with the following message, I can then relaunch the command, it downloads some more picture and then stops again:

2023-09-03 11:07:13 INFO     Downloaded /media/mario/iCloudpd/2009/11/MVI_1093.MOV                                                                                         
Traceback (most recent call last):                                                                                                                                         
  File "urllib3/connectionpool.py", line 714, in urlopen
  File "urllib3/connectionpool.py", line 403, in _make_request
  File "urllib3/connectionpool.py", line 1053, in _validate_conn
  File "urllib3/connection.py", line 419, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1075, in _create
  File "ssl.py", line 1346, in do_handshake
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 798, in urlopen
  File "urllib3/util/retry.py", line 550, in increment
  File "urllib3/packages/six.py", line 769, in reraise
  File "urllib3/connectionpool.py", line 714, in urlopen
  File "urllib3/connectionpool.py", line 403, in _make_request
  File "urllib3/connectionpool.py", line 1053, in _validate_conn
  File "urllib3/connection.py", line 419, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1075, in _create
  File "ssl.py", line 1346, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 5, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 299, in main
  File "icloudpd/base.py", line 847, in core
  File "tqdm/std.py", line 1178, in __iter__
  File "pyicloud_ipd/services/photos.py", line 295, in photos
  File "pyicloud_ipd/services/photos.py", line 276, in photos_request
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 71, in request
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[5569] Failed to execute script 'icloudpd' due to unhandled exception!

## Context
I have 2FA active and I tried downloading in different folders and not using a customized folder structure.

Thanks!

**Comment by AndreyNikiforov** [comment]
Were you able to download anything yet? If yes, then error is intermittent and may be related to your ISP (or Apple resetting connection). If you never got any bits downloaded yet, then connectivity to apple servers may the main reason. 

Note that if you are connecting from mainland China, Apple servers are not reachable without extra setup.

**Comment by mariomaz87** [comment]
> Were you able to download anything yet? If yes, then error is intermittent and may be related to your ISP (or Apple resetting connection). If you never got any bits downloaded yet, then connectivity to apple servers may the main reason.
> 
> Note that if you are connecting from mainland China, Apple servers are not reachable without extra setup.

I can download the photos, even if in different sessions and I’m not in China. Thanks, so I guess this error is not strictly related the icloudpd. Strange because I don’t have other issues with my isp, so maybe it’s something on Apple side!
