### ISSUE TITLE
Listing libraries returns INTERNAL_ERROR

### ISSUE THREAD

**Issue by gklka** [icloud-photos-downloader/icloud_photos_downloader#690]
## Overview

First of all, thank you for the shared libraries support! I was really looking forward for it.

Using `--list-libraries` switch results the following:

## Steps to Reproduce

```
 $ sudo /opt/icloudpd/bin/icloudpd --directory /mnt/disk7/iCloud \
           --username **** \
           --password **** \
           --list-libraries
2023-09-26 07:49:43 DEBUG    Authenticating...
2023-09-26 07:49:47 ERROR    INTERNAL_ERROR (INTERNAL_ERROR)
Traceback (most recent call last):
  File "/opt/icloudpd/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/icloudpd/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/icloudpd/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/icloudpd/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/icloudpd/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/icloudpd/lib/python3.10/site-packages/icloudpd/base.py", line 313, in main
    core(
  File "/opt/icloudpd/lib/python3.10/site-packages/icloudpd/base.py", line 767, in core
    libraries_dict = icloud.photos.libraries
  File "/opt/icloudpd/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 277, in libraries
    libraries[zone_name] = PhotoLibrary(
  File "/opt/icloudpd/lib/python3.10/site-packages/pyicloud_ipd/services/photos.py", line 154, in __init__
    request = self.service.session.post(
  File "/opt/icloudpd/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/opt/icloudpd/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: INTERNAL_ERROR (INTERNAL_ERROR)
``` 

## Expected Behavior
List my shared libraries

## Actual Behavior
Throws an exception

**Comment by gus-abreu** [comment]
On the road with only a Windows machine, but I was able to reproduce:
```
PS C:\Users\gTo\Downloads> .\icloudpd-1.16.0-windows-amd64.exe --list-libraries
iCloud username/email: ******
2023-09-26 09:59:14 DEBUG    Authenticating...
iCloud Password:
2023-09-26 09:59:27 ERROR    INTERNAL_ERROR (INTERNAL_ERROR)
Traceback (most recent call last):
  File "starters\icloudpd.py", line 5, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 313, in main
  File "icloudpd\base.py", line 767, in core
  File "pyicloud_ipd\services\photos.py", line 277, in libraries
  File "pyicloud_ipd\services\photos.py", line 154, in __init__
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\base.py", line 105, in request
  File "pyicloud_ipd\base.py", line 127, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: INTERNAL_ERROR (INTERNAL_ERROR)
[20588] Failed to execute script 'icloudpd' due to unhandled exception!
```
```
PS C:\Users\gTo\Downloads> .\icloudpd-1.16.0-windows-amd64.exe --list-albums
iCloud username/email: *****
2023-09-26 10:01:38 DEBUG    Authenticating...
iCloud Password:
2023-09-26 10:01:48 ERROR    INTERNAL_ERROR (INTERNAL_ERROR)
2023-09-26 10:01:48 ERROR    error?? INTERNAL_ERROR (INTERNAL_ERROR)
PS C:\Users\gTo\Downloads> .\icloudpd-1.16.0-windows-amd64.exe
```
```
PS C:\Users\gTo\Downloads> .\icloudpd-1.16.0-windows-amd64.exe -d . --dry-run
iCloud username/email: *****
2023-09-26 10:02:45 DEBUG    Authenticating...
iCloud Password:
2023-09-26 10:02:54 ERROR    INTERNAL_ERROR (INTERNAL_ERROR)
2023-09-26 10:02:54 ERROR    error?? INTERNAL_ERROR (INTERNAL_ERROR)
```

Works as expected using 1.15.1:
```
PS C:\Users\gTo\Downloads> .\icloudpd-1.15.1-windows-amd64.exe --list-albums
iCloud username/email: *****
2023-09-26 10:08:31 DEBUG    Authenticating...
iCloud Password:
All Photos
Time-lapse
[...]
```

**Comment by gklka** [comment]
Tonight I will test the change you mentioned, and report if it is working. Let me know if I can help you in anything more.

**Comment by gklka** [comment]
Changing the URL in `libraries()` call in `pyicloud_ipd/services/photos.py:261` to `url = ('%s/zones/list' %` worked!

Now both `--list-libraries` and sync using `--library <received id>` works!

**Comment by fver** [comment]
good news, adapted code and tests. Tried to update the pull request.

**Comment by fver** [comment]
PR submitted, could not do any further testing on this. If somebody has an idea how to better validate this, please let us know.
