### ISSUE TITLE
2FA throw errors

### ISSUE THREAD

**Issue by latel** [icloud-photos-downloader/icloud_photos_downloader#804]
## Overview
I cannot intialize, there is an error arise when apple sends me 2fa code.

## Steps to Reproduce
1. deploy docker on unraid by https://github.com/Womabre/unraid-docker-templates
2. initialize

## Expected Behavior
able to initialize with 2fa

## Actual Behavior
apple popup 2fa code on my macbook, but error is thrown in console, no where to enter 2fa code
```
$ docker exec -it icloudpd sync-icloud.sh --Initialise

2024-03-27 11:27:23 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.718 started *****
2024-03-27 11:27:23 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-03-27 11:27:23 INFO     Alpine Linux 3.19.0
2024-03-27 11:27:23 INFO     Python version: 3.11.6
2024-03-27 11:27:23 INFO     Loading configuration from: /config/icloudpd.conf

2024-03-27 11:27:33 INFO     Apple ID: xxxx@icloud.com
2024-03-27 11:27:33 INFO     Authentication Type: MFA
2024-03-27 11:27:33 INFO     Cookie path: /config/xxxxicloudcom
2024-03-27 11:27:33 INFO     Cookie expiry notification period: 7
2024-03-27 11:27:33 INFO     Download destination directory: /home/user/iCloud
2024-03-27 11:27:33 INFO     Folder structure: {:%Y/%m/%d}
2024-03-27 11:27:33 INFO     Synchronisation interval: 86400
2024-03-27 11:27:33 INFO     Synchronisation delay (minutes): 0
2024-03-27 11:27:33 INFO     Set EXIF date/time: false
2024-03-27 11:27:33 INFO     Auto delete: false
2024-03-27 11:27:33 INFO     Delete after download: false
2024-03-27 11:27:33 INFO     Photo size: original
2024-03-27 11:27:33 INFO     Single pass mode: false
2024-03-27 11:27:33 INFO     Skip download check: false
2024-03-27 11:27:33 INFO     Skip live photos: false
2024-03-27 11:27:33 INFO     Number of most recently added photos to download: Download All Photos
2024-03-27 11:27:33 INFO     Downloading photos from: Download All Photos
2024-03-27 11:27:33 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024-03-27 11:27:33 INFO     Live photo size: original
2024-03-27 11:27:33 INFO     Skip videos: false
2024-03-27 11:27:33 INFO     Convert HEIC to JPEG: false
2024-03-27 11:27:33 INFO     Downloading from: icloud.com
2024-03-27 11:27:33 INFO     Authentication domain: com
2024-03-27 11:27:33 INFO     Ignore Synology extended attribute directories: Disabled
2024-03-27 11:27:34 INFO     Script launch parameters: --Initialise
2024-03-27 11:27:34 WARNING  Group id, 100, already in use by the group: users - continuing as force_gid variable has been set. Group name to use: users
Enter iCloud password for xxxx@icloud.com: 
Traceback (most recent call last):
  File "starters/icloud.py", line 5, in <module>
  File "pyicloud_ipd/cmdline.py", line 200, in main
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[926] Failed to execute script 'icloud' due to unhandled exception!
2024-03-27 11:27:44 ERROR    Keyring file does not exist. Please try again.
```

## Context
using https://github.com/Womabre/unraid-docker-templates

**Comment by latel** [comment]
solved with https://github.com/boredazfcuk/docker-icloudpd/issues/336
