### ISSUE TITLE
The China region ID login shows an authentication error

### ISSUE THREAD

**Issue by randomatom** [icloud-photos-downloader/icloud_photos_downloader#819]
I am running the program in an Ubuntu 22.04 environment with Docker. Version: 1.17.4. The ID in the China region cannot be used normally, while the ID in the US region functions normally.
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. run:  
Operating environment ubuntu 22.04
Version：1.17.4
```
docker run -it --rm --name icloudpd \
  -v /mnt/nas/home/icloud/xxx:/data \
  -e TZ=CST-8  \
  -e auth_china=True \
  icloudpd/icloudpd:latest icloudpd  \
  --directory /data \
  --domain cn \
  --watch-with-interval 3600
```
4. Enter Apple ID for the China region.
5. The phone prompts for two-factor authentication.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Can log in.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

```
2024-04-17 16:38:03 DEBUG    Authenticating...
iCloud Password:
2024-04-17 16:38:12 INFO     Two-step/two-factor authentication is required (2fa)
2024-04-17 16:38:13 ERROR    Authentication required for Account. (500)
Traceback (most recent call last):
  File "starters/icloudpd_ex.py", line 110, in <module>
  File "starters/icloudpd_ex.py", line 106, in main
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 326, in main
  File "icloudpd/base.py", line 757, in core
  File "icloudpd/authentication.py", line 48, in authenticate_
  File "icloudpd/authentication.py", line 104, in request_2fa
  File "pyicloud_ipd/base.py", line 486, in trusted_devices
  File "requests/sessions.py", line 602, in get
  File "pyicloud_ipd/base.py", line 132, in request
  File "pyicloud_ipd/base.py", line 134, in request
  File "pyicloud_ipd/base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (500)
[8] Failed to execute script 'icloudpd_ex' due to unhandled exception!
```

## Context
[NOTE]: # ( Give us any additional information you may have. )
Can log in normally with a US region Apple ID.

**Comment by AndreyNikiforov** [comment]
Did it work for 1.17.3 or earlier versions?

**Comment by randomatom** [comment]
Using version 1.17.4 or latest does not work.

**Comment by randomatom** [comment]
Version 1.77.3 can run

**Comment by betacat-ha** [comment]
The same problem exists with Apple ID in mainland China. The Apple ID in Taiwan is working properly.

Tested: 1.17.3 & 1.17.4 (Docker & macOS)

```
2024-04-27 08:46:12 DEBUG    Authenticating...
2024-04-27 08:46:13 ERROR    Authentication required for Account. (421)
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 760, in core
  File "icloudpd/authentication.py", line 31, in authenticate_
  File "pyicloud_ipd/base.py", line 305, in __init__
  File "pyicloud_ipd/base.py", line 367, in authenticate
  File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?
[6965] Failed to execute script 'icloudpd' due to unhandled exception!
```

**Comment by betacat-ha** [comment]
我发现这个函数在登录时返回了500错误，但是Web版的iCloud现在似乎没有检查信任设备的数量，还需要检查这个吗？

Translation: I noticed that this function is returning a 500 error when logging. Should we verify the count of trusted devices? It appears that iCloud Web isn't  currently performing this check.

```
    def trusted_devices(self):
        """ Returns devices trusted for two-step authentication."""
        request = self.session.get(
            '%s/listDevices' % self.SETUP_ENDPOINT,
            params=self.params
        )
        return request.json().get('devices')
```

**Comment by AndreyNikiforov** [comment]
> 
> Translation: I noticed that this function is returning a 500 error when logging. Should we verify the count of trusted devices? It appears that iCloud Web isn't currently performing this check.
> 

I also noticed that icloud.com Web access does not use `listDevices` call anymore, however that request works for `icloudpd` in US. IIUC that request does not work in China. One easy option I see is to make that request fail silently.

**Comment by AndreyNikiforov** [comment]
@betacat-ha pls check if 1.17.5 solves the issue with `listDevices` call from China.

**Comment by betacat-ha** [comment]
> @betacat-ha pls check if 1.17.5 solves the issue with `listDevices` call from China.

Tested on macOS with no errors found. Thanks for your efforts!
