### ISSUE TITLE
ERROR    Invalid username/password combination. (401)

### ISSUE THREAD

**Issue by Vig2OOO** [icloud-photos-downloader/icloud_photos_downloader#830]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Receiving an error saying invalid username/password combination, even though credentials are 100% correct.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ran `icloudpd -l`
2. Entered icloud email and password
3. Received `ERROR Invalid username/password combination. (401)`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

To get started with `icloudpw`.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Username/password error as above.

## Context
[NOTE]: # ( Give us any additional information you may have. )

```
C:\WINDOWS\system32>icloudpd -l
iCloud username/email: XXXXX@icloud.com
2024-05-01 21:00:29 DEBUG    Authenticating...
iCloud   ##Password:
2024-05-01 21:00:35 ERROR    Invalid username/password combination. (401)
Traceback (most recent call last):
  File "pyicloud_ipd\base.py", line 357, in authenticate
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\base.py", line 140, in request
  File "pyicloud_ipd\base.py", line 207, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Invalid username/password combination. (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters\icloudpd.py", line 6, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 326, in main
  File "icloudpd\base.py", line 757, in core
  File "icloudpd\authentication.py", line 31, in authenticate_
  File "pyicloud_ipd\base.py", line 305, in __init__
  File "pyicloud_ipd\base.py", line 365, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Invalid username/password combination. (401)'))
[29888] Failed to execute script 'icloudpd' due to unhandled exception!
```

**Comment by AndreyNikiforov** [comment]
What version of `icloudpd` are you using? Have it ever worked before and what changed?

**Comment by Vig2OOO** [comment]
> What version of `icloudpd` are you using? Have it ever worked before and what changed?

I am using the latest version, v1.17.5, and this is the very first time that I am using `icloudpd`.

**Comment by Vig2OOO** [comment]
Bump, still encountering this error unfortunately.

**Comment by AndreyNikiforov** [comment]
From what I can tell, Apple responds to your user/password combo as "Invalid email/password combination." and `icloudpd` just displays it to you. I don't see anybody else reporting this issue, so this is most likely related to your account/setup.

Ideas what to check/try:
- any special chars in email or password?
- any special auth setup (FIDO, ADP etc)?

**Comment by Vig2OOO** [comment]
As an update, this issue is now resolved.  It seems like something went haywire when I copied and pasted my password in the prompt, hence the password error.  I then manually typed in my password and then the script was able to run successfully.
