### ISSUE TITLE
System Keyring Error

### ISSUE THREAD

**Issue by Vig2OOO** [icloud-photos-downloader/icloud_photos_downloader#834]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Trying to save iCloud username and password in the system keyring as per the instructions found [here](https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/FAQ.md#system-keyring), but receiving the error below.  Using Windows if that's relevant.  Any idea what the problem could be based on this output (with secrets XXXXXX'ed out).

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
```
C:\WINDOWS\system32>icloud --username XXXXXX@icloud.com

Two-step authentication required.
Please enter validation code
(string) --> XXXXXX

Traceback (most recent call last):
  File "starters\icloud.py", line 5, in <module>
  File "pyicloud_ipd\cmdline.py", line 279, in main
  File "pyicloud_ipd\base.py", line 589, in devices
  File "pyicloud_ipd\services\findmyiphone.py", line 28, in __init__
  File "pyicloud_ipd\services\findmyiphone.py", line 67, in refresh_client
pyicloud_ipd.exceptions.PyiCloudNoDevicesException
[53352] Failed to execute script 'icloud' due to unhandled exception!
```

**Comment by AndreyNikiforov** [comment]
Do you have trusted device for your account? What version of `icloud` are you using? BTW password will be saved to keyring when using `icloudpd` as well, see [doc](https://icloud-photos-downloader.github.io/icloud_photos_downloader/authentication.html#password-providers)
