### ISSUE TITLE
Authentication failure - failed to parse response with JSON mimetype

### ISSUE THREAD

**Issue by fearaschiarrai** [icloud-photos-downloader/icloud_photos_downloader#837]
## Overview
Failing to parse response with JSON mimetype (after enter password and 2FA 

## Steps to Reproduce
Upgraded to version 1.17.5  (using pip) before running .
1. icloudpd --directory c:/Photos --username <myusername> --list-albums
2. enter password
3. enter 2FA

## Expected Behavior
worked ok when I last used in November 20023 (version?). successfully downloaded my pictures and videos

## Actual Behavior
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 714, in urlopen
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 461, in _make_request
  File "http\client.py", line 1428, in getresponse
  File "http\client.py", line 331, in begin
  File "http\client.py", line 300, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 798, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 714, in urlopen
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 461, in _make_request
  File "http\client.py", line 1428, in getresponse
  File "http\client.py", line 331, in begin
  File "http\client.py", line 300, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "starters\icloudpd.py", line 6, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 326, in main
  File "icloudpd\base.py", line 757, in core
  File "icloudpd\authentication.py", line 31, in authenticate_
  File "pyicloud_ipd\base.py", line 305, in __init__
  File "pyicloud_ipd\base.py", line 319, in authenticate
  File "pyicloud_ipd\base.py", line 423, in _validate_token
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\base.py", line 77, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[11964] Failed to execute script 'icloudpd' due to unhandled exception!

## Context
password and 2fa verified as correct
unsure of what version of icloudpd I ran when successful in Nov 2023

**Comment by AndreyNikiforov** [comment]
Errors suggest that Apple closes connection and no reasons are given. Are you still having the issue or it resolved by itself?

**Comment by latonita** [comment]
I'm having the same error when doing re-auth however this doesn't affect updating cookie and loading photos

**Comment by AndreyNikiforov** [comment]
fixed 1.18.0

**Comment by fearaschiarrai** [comment]
actually I tried again a few days later and used \ instead of / in the path name .. and it worked :) not certain if this was the reason.
