### ISSUE TITLE
could not decrypt pcs cookie

### ISSUE THREAD

**Issue by mikewei** [icloud-photos-downloader/icloud_photos_downloader#880]
## Overview

I got the error below after authentication: 
Internal error (could not decrypt pcs cookie)

thanks

## Steps to Reproduce

$ icloudpd --username ... --auth-only
2024-06-25 12:47:45 DEBUG    Authenticating...
2024-06-25 12:47:50 INFO     Authentication completed successfully

$ icloudpd --directory /data/icloudpd --username ...  --watch-with-interval 3600
2024-06-25 12:46:35 DEBUG    Authenticating...
2024-06-25 12:46:41 ERROR    could not decrypt pcs cookie (INTERNAL_ERROR)
Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 499, in main
  File "icloudpd/base.py", line 983, in core
  File "pyicloud_ipd/base.py", line 477, in photos
  File "pyicloud_ipd/services/photos.py", line 279, in __init__
  File "pyicloud_ipd/services/photos.py", line 166, in __init__
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/session.py", line 168, in request
  File "pyicloud_ipd/session.py", line 197, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: could not decrypt pcs cookie (INTERNAL_ERROR)

**Comment by jessedc** [comment]
I received this error when running the command for the first time, but subsequent runs a few minutes later were successful. Have you been able to get past this issue?
