### ISSUE TITLE
Authentication required for account. (421); Invalid username/password combination. (401) error

### ISSUE THREAD

**Issue by 22408aaron** [icloud-photos-downloader/icloud_photos_downloader#930]
I'm trying to download some photos, and I keep getting the aforementioned errors, both with an app-specific password and my iCloud password. Below is the response after running an icloudpd command (both with my typical flags, and the --auth-only flag). 
FYI, this is on the latest build (1.23.0) and Windows amd64. I do have 2FA enabled too, and what I've done below worked last time I tried it (a week or two ago). 

`E:\icloudpd.exe --username <email> --password <password> --auth-only`

`2024-08-07 17:54:12 DEBUG    Authenticating...
2024-08-07 17:54:13 ERROR    Authentication required for Account. (421)
2024-08-07 17:54:14 ERROR    Invalid username/password combination. (401)
Traceback (most recent call last):
  File "pyicloud_ipd\base.py", line 211, in authenticate
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\session.py", line 128, in request
  File "pyicloud_ipd\session.py", line 196, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Invalid username/password combination. (401)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "starters\icloudpd.py", line 6, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 696, in main
  File "icloudpd\base.py", line 1130, in core
  File "icloudpd\authentication.py", line 53, in authenticate_
  File "pyicloud_ipd\base.py", line 157, in __init__
  File "pyicloud_ipd\base.py", line 219, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Invalid username/password combination. (401)'))
[10528] Failed to execute script 'icloudpd' due to unhandled exception!`

**Comment by AndreyNikiforov** [comment]
Apple app-specific password did not with iCloud photos last time I checked. If your username/password works with icloud.com, if should work with `icloudpd` because the latter just emulates the former. Reading through [auth section in the doc](https://icloud-photos-downloader.github.io/icloud_photos_downloader/authentication.html) may help finding the root cause for your errors.
