### ISSUE TITLE
‘Missing apple_id field！’This problem has been bothering me for a long time, who can help me?Can’t it be used without 2fa certification?

### ISSUE THREAD

**Issue by 14278358** [icloud-photos-downloader/icloud_photos_downloader#957]
C:\Users\abcabc>icloudpd --directory C:\Users\5257\Desktop\PyCharm\pythonProject\icloud_photos --username abcabc@icloud.com --password abcabc --recent 10 --log-level debug
2024-09-23 17:15:11 DEBUG    Authenticating...
2024-09-23 17:15:14 ERROR    Missing apple_id field (Missing apple_id field)
Traceback (most recent call last):
  File "pyicloud_ipd\base.py", line 241, in _authenticate_with_token
  File "requests\sessions.py", line 637, in post
  File "pyicloud_ipd\session.py", line 167, in request
  File "pyicloud_ipd\session.py", line 196, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Missing apple_id field (Missing apple_id field)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters\icloudpd.py", line 6, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "icloudpd\base.py", line 745, in main
  File "icloudpd\base.py", line 1179, in core
  File "icloudpd\authentication.py", line 53, in authenticate_
  File "pyicloud_ipd\base.py", line 157, in __init__
  File "pyicloud_ipd\base.py", line 221, in authenticate
  File "pyicloud_ipd\base.py", line 247, in _authenticate_with_token
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field (Missing apple_id field)'))
[5832] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by AndreyNikiforov** [comment]
[Dup] Search for this error in the issues for this repo - you may have idea what is causing it for your account, e.g. #920, #770  

Note about 2fa: once enabled for account, it cannot be turned off. New accounts must have 2fa enabled.
