### ISSUE TITLE
KeyError: 'salt' occurs after enter the password

### ISSUE THREAD

**Issue by neverbiasu** [icloud-photos-downloader/icloud_photos_downloader#983]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
python version is: 3.9.12
icloudpd version is: 1.24.1

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. run `pip install icloudpd`
2. run  `icloudpd --directory DIRECTORY --username USERNAME --watch-with-interval 3600`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
```
2024-11-01 16:34:20 DEBUG    Authenticating...
iCloud Password: 
Traceback (most recent call last):
  File "/opt/anaconda3/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/icloudpd/base.py", line 745, in main
    result = core(
  File "/opt/anaconda3/lib/python3.9/site-packages/icloudpd/base.py", line 1183, in core
    icloud = authenticator(
  File "/opt/anaconda3/lib/python3.9/site-packages/icloudpd/authentication.py", line 53, in authenticate_
    icloud = PyiCloudService(
  File "/opt/anaconda3/lib/python3.9/site-packages/pyicloud_ipd/base.py", line 160, in __init__
    self.authenticate()
  File "/opt/anaconda3/lib/python3.9/site-packages/pyicloud_ipd/base.py", line 240, in authenticate
    salt = base64.b64decode(body['salt'])
KeyError: 'salt'
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

**Comment by maihacke** [comment]
Login is also not working for me, but with a different error message:

simon@cubietruck:/data/backup/icloud$ icloudpd --username ***** -d DIR --watch-with-interval 3600
2024-11-01 10:31:08 DEBUG    Authenticating...
iCloud Password: 
2024-11-01 10:31:13 ERROR    Authentication required for Account. (421)
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 270, in authenticate
pyicloud_ipd.exceptions.PyiCloudAPIResponseException: {
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
} (401)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1183, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 160, in __init__
  File "pyicloud_ipd/base.py", line 280, in authenticate
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[362551] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by AndreyNikiforov** [comment]
The error suggests that response from Apple was in unexpected format. Are you experiencing this error consistently?

**Comment by AndreyNikiforov** [comment]
no action from the requestor
